### ISSUE TITLE
uninitialized constant AWS::Errors

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/paperclip#1837] opened 2015-04-21 20:27 UTC
I've been getting an `uninitialized constant AWS::Errors` exception when attempting to save a file using Paperclip and the `aws-sdk` gem. The stacktrace says it's happening [here](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L301).

I've got `aws-sdk v2.0.39` and `paperclip v4.2.1` installed.

I'm not exactly sure what changed on the `aws-sdk` side. Their repo is a little confusing and I don't have a ton of time to dig into it but I can't find `AWS::Errors::Base` or even `AWS::Errors` in their codebase. I was able to find `Aws::Errors` but not `Aws::Errors::Base`.

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/errors.rb

Not sure if that's even the relevant portion.

Here's my stack trace:

```
uninitialized constant AWS::Errors
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/storage/s3.rb:301:in `rescue in exists?'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/storage/s3.rb:296:in `exists?'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:557:in `block in queue_all_for_delete'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:556:in `map'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:556:in `queue_all_for_delete'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:250:in `clear'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:102:in `assign'
	from /app/vendor/bundle/ruby/2.2.0/gems/paperclip-4.2.1/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
	from /app/app/services/user_account/create_vcard.rb:7:in `call'
	from (irb):5:in `block in irb_binding'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
	from (irb):5
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
```

Let me know if there's anymore information I can provide.

**Comment by betesh** [comment] 2015-04-22 19:54
duplicates #1764

**Comment by tute** [comment] 2015-05-20 03:26
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1764. Thanks for reporting!

**Closed by tute** 2015-05-20 03:27 UTC
