### ISSUE TITLE
Specifying '#' in Geometry String Raises an Error

### ISSUE THREAD

**Issue by Smolations** [thoughtbot/paperclip#1664] opened 2014-09-30 18:37 UTC
Our machines (including dependencies for paperclip):
* Young Macbook Pros running Mavericks 10.9.x (mostly the current 10.9.5)
* ImageMagick 6.8.9-7

I work with a full team of developers building an SOA application. One feature of the application allows for users to upload images, so we gave paperclip a try. We mostly rely on homebrew for software installs, but some insist upon MacPorts). As we were testing the new functionality, we ran across the common `Paperclip::Errors::NotIdentifiedByImageMagickError` error. We tried to reinstall both the `libtool` and `jpeg` packages, neither of which fixed the issue. After investigating, it appears that [at least] `libtool` is among the few homebrew packages which _renames_ the binaries it installs by prepending a character to the file name (e.g. `glibtool`). The explanation given by homebrew is that the installed binary would conflict with the system binary. This behavior indicates that these particular binaries could inject possible risk into the operating system itself. Simply symlinking the renamed binary to match the system binary in order to override it is undesirable because of that risk.

Luckily, I had a vagrant machine set up for the application running Ubuntu 14.04. I installed imagemagick in the VM and that error disappeared. However, another error, which is the topic of this issue, arose. We were attempting to generate thumbnail images thusly:

    def styles

        ret = {
          :thumb => ["250x250#>"]
        }

        case self.media_file_application_type
          when "banner"
            ret[:original] = ["360x100#"]  # If banner, save over the original
        end

        ret
    end

And this is the error message received:

    Command :: convert '/tmp/7d97481b1fe66f4b51db90da7e794d9f20140930-1541-ybmg9a.jpeg[0]' -auto-orient -resize "250x250#" -quality 100 -strip '/tmp/7d97481b1fe66f4b51db90da7e794d9f20140930-1541-ybmg9a20140930-1541-1icq67m'
    convert.im6: invalid argument for option `-resize': 250x250# @ error/convert.c/ConvertImageCommand/2382.
    [paperclip] An error was received while processing: #<Paperclip::Error: There was an error processing the thumbnail for 7d97481b1fe66f4b51db90da7e794d9f20140930-1541-ybmg9a>

There are examples of using the '#' syntax to specify geometry in the paperclip README, but no mention of what it does. There is a link provided in the README to see more about defining styles. It takes the user to the imagemagick documentation for specifying geometries. **Nowhere in the imagemagick documentation is the '#' specified, nor explained.** I am surprised I have not seen this issue already reported. This particular syntax does not seem to be supported by imagemagick, at least in the most current version. This issue is to request that the paperclip README be updated in order to prevent other users from encountering this error in the future, or to at least specify which versions of imagemagick, if any, support that syntax.

**Comment by tute** [comment] 2015-05-15 19:11
Thanks for reporting @Smolations! Would you send a PR fixing this please? Thank you!

**Comment by tute** [comment] 2015-05-29 02:22
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1313. Thanks for your report!

**Closed by tute** 2015-05-29 02:22 UTC
Labels: Docs
