### ISSUE TITLE
Paperclip::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by tjlahr** [thoughtbot/paperclip#1223] opened 2013-04-19 22:37 UTC
On my Rails/Spree application on an AWS development server, I'm getting:
`Paperclip::NotIdentifiedByImageMagickError in Admin/imagesController#create` when I try to upload product images.

Spree's issue tracker suggest this happens with Paperclip < 2.8. StackOverflow says I should update `Paperclip.options[:command_path]` to the value of `which identify`. On this tracker and Spree's people have said that's is due using the latest version of cocaine.

None of those solutions have worked and I'm not sure the best way to debug. I'm using Paperclip 2.8.0 and cocaine 0.3.1 (it also broke with 0.5.x).

There's been a lot of chatter about this problem, but I don't see a definitive answer. Would love to help however I can.

**Comment by maclover7** [comment] 2015-03-09 21:45
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by lachlanjc** [comment] 2015-03-10 00:02
@maclover7 I'm not having any problems, even with sizes specified. Thanks for checking in though.

**Comment by maclover7** [comment] 2015-03-10 00:07
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by JaredCowan** [comment] 2015-03-18 20:44
Im still having this problem

**Comment by edipofederle** [comment] 2015-05-05 18:09
+1 here

**Comment by tute** [comment] 2015-05-29 02:20
Closing as duplicate of: https://github.com/thoughtbot/paperclip/issues/1313. We are busy right now, please send a PR if you have availability to solve this issue! Thank you, all.

**Closed by tute** 2015-05-29 02:20 UTC

**Comment by leeizamo** [comment] 2015-08-02 08:46
I'm using an Ubuntu machine and can't seem to find a straightforward solution to this error: (Paperclip::Errors::NotIdentifiedByImageMagickError) Everything works fine with the styles removed... and I've tried a lot of iterations with suggestions on others sites and still stuck... any help would be appreciated!

**Comment by dpritchett** [comment] 2015-08-05 20:59
@leeizamo I just had the same error crop up for me but the only time it happened was when I was `reprocess!`ing and image off of S3.  Turns out the image dimensions check first redownloads the image from S3 into `/tmp` and then tries to check its size using local ImageMagick tools (`file -b --mime /tmp/filenamehere`.  For reasons unkown to me the tmp file was there but its length was 0.

On a lark I tried messing with a few different versions of `aws-sdk`.

Pinning my `aws-sdk` version to `~> 1.6` [as mentioned in a comment in Paperclip's S3 class](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L7) seems to have fixed it.

**Comment by jrochkind** [comment] 2016-06-29 15:26
I am getting this error with Geometry on an svg file. I debugged to see:

~~~
$ identify -format '%wx%h,%[exif:orientation]' '/var/folders/8m/dfpc7lkn13jcr48djzj3crgh0000gn/T/a85ed8a515e48fa1a09ee4e6982a0a9020160629-20022-uopf1q.svg[0]'
identify: not authorized /var/tmp/magick-20976fVu2dz9MXGJo @ error/constitute.c/ReadImage/412`. 
~~~

I discovered by playing around with the command line that it is for some reason the `%[exif:orientation]` that triggers ImageMagick to complain about auth. If I remove `exif:orientation` from the command line, it works. 

I can get Paperclip to stop generating this by `Paperclip.options[:use_exif_orientation] = false`. I don't know if that's really a good idea, but it gets me going again. 

I don't understand entirely what's going on -- is looking at EXIF data on an SVG a possibly dangerous operation (does SVG even have EXIF?)? Is it correct for imagemagick to refuse to do this? Is there any way to get paperclip to skip it for SVG's, but not for other file types where it may not be dangerous and imagemagick may be willing to do it?

**Comment by bhfailor** [comment] 2016-10-21 23:24
I had the same experience that @vitchell mentioned previously.  Changing to a different file avoided the error (both files are attached to this comment).

A file worked for a while and then stopped working in RSpec tests.  The file continued to work in rails (a_pdf_document.pdf).

Created a new file and it works in both rails and RSpec, at least for now (z_pdf_document.pdf).

Debian 8 (jessie)
paperclip (4.3.0)
ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01
rspec-rails (3.4.1)
spring-commands-rspec (1.0.4)
rails (4.2.3)

[a_pdf_document.pdf](https://github.com/thoughtbot/paperclip/files/545414/a_pdf_document.pdf)
[z_pdf_document.pdf](https://github.com/thoughtbot/paperclip/files/545416/z_pdf_document.pdf)
