### ISSUE TITLE
Memory error when programmatically attaching image to model using Paperclip in Rails 4

### ISSUE THREAD

**Issue by Corstiaan84** [thoughtbot/paperclip#2092] opened 2016-01-19 07:22 UTC
I'm trying to programmatically attach a file to a model using Paperclip in Rails 4. Here's my (simplified) code:

````
def set_image
    File.open('public/images/file.jpg') do |f|
        self.image = f
      end
end
````

This results in the following error:

````
error=#<Paperclip::Error: There was an error processing the thumbnail for 7e68013308796b15dc17c274476e2aa820160118-18893-9gvotp
````

Could this be due to some resize/imagemagick settings perhaps? Here's my config:

````
class Item < ActiveRecord::Base
    has_attached_file :image, styles: { header: "1464x100000#", large: "300x300#", thumb: "100x100#", xs: "40x40#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    validates_with AttachmentSizeValidator, attributes: :image, less_than: 3.megabytes
end
````

Also, when I run this locally the terminal starts prompting me with memory errors regarding the swap size on the startup disk? (Mac os x) There is plenty memory available though.

Using Paperclip to attach and resize image from a form post works as expected.

Any ideas? Thanks :-)

**Comment by Corstiaan84** [comment] 2016-01-21 12:02
After lots of face palms I decided to implement CarrierWave. This worked as expected.

Not trying to diss Paperclip. Just making sure other people stumbling across this can move forward.

**Comment by kevcha** [comment] 2016-01-27 11:29
According to http://stackoverflow.com/a/26849250/1386619, you need ~ `1464 * 100000 * 8 = 1171200000 = 1.17 Gbytes` to make the `header` version.
Depending on your available memory on your machine, the error is maybe not so unexpected.

Are you sure you want to have a 100 000px height header version ? Large, thumb, and xs versions are processing well.

**Comment by Corstiaan84** [comment] 2016-01-27 11:40
Hi @kevcha,

Well, that might shed some light on the issues, yes. However, given the constraints, the height of the image should never actually be 100000px as the width would not allow for it unless the user uploads an image that by some chance is actually 1464 * 100000, correct? I know this is not the most elegant solution but from what I have read its common though.

Does Paperclip or imagemagick perhaps allocate the max needed memory in advance, even if the actual resized image will be much less high than 100 000px? Still, I do have enough available memory that it should be able to handle it (not that this is a desirable situation under any circumstance).

Thanks for your reply :-)

**Comment by sikachu** [comment] 2016-02-08 16:42
>Does Paperclip or imagemagick perhaps allocate the max needed memory in advance, even if the actual resized image will be much less high than 100 000px? Still, I do have enough available memory that it should be able to handle it (not that this is a desirable situation under any circumstance).

I think it does, and that's possibly why you're running into this issue.

You should be seeing a command that Paperclip runs in your Rails log. Have you tried issue that command on your console and see if you are having the same result?

**Comment by kevcha** [comment] 2016-02-09 10:18
@sikachu @Corstiaan84 When trying in my local environement, here is what Paperclip tells me : 

![screen shot 2016-02-09 at 11 08 20](https://cloud.githubusercontent.com/assets/472453/12913236/c0c3ed1e-cf1d-11e5-9067-44e2175674aa.png)

Then trying to convert only using imagemagick : 

![screen shot 2016-02-09 at 11 12 11](https://cloud.githubusercontent.com/assets/472453/12913271/ff8fdc24-cf1d-11e5-9c66-0eeaa665138a.png)

The image magick error `unable to extend cache '/Users/kevcha/desktop/foo.png': No space left on device @ error/cache.c/OpenPixelCache/3728` is rescued in paperclip [here](https://github.com/thoughtbot/paperclip/blob/523bd46c768226893f23889079a7aa9c73b57d68/lib/paperclip/thumbnail.rb#L81) and results in the `There was an error processing the thumbnail for ...`

So it seems to be an image magick related issue, not a paperclip one.
Playing with parameters to the `convert` image magick command let me think that the `1464x100000 px` request for image dimension is too high. It works well with "classics" dimensions.

**Comment by tute** [comment] 2016-08-19 03:27
Closing this issue, as it is not a bug in paperclip. Thank you for your report.

**Closed by tute** 2016-08-19 03:27 UTC
Labels: Bug
