### ISSUE TITLE
Double reporting validation errors

### ISSUE THREAD

**Issue by iDiogenes** [thoughtbot/paperclip#2040] opened 2015-11-07 03:09 UTC
I am running rails 4.1 with the head of paperclip master and the size validation errors are displaying two of the same error. I have tried validates_attachment and validates_attachment_size and both produce the same issue:

```
validates_attachment_size :logo, less_than: 1.megabytes
validates_attachment :logo, content_type: { content_type: /\Aimage/ }, size: { less_than: 1.megabytes }
```

![screen shot 2015-11-06 at 6 51 24 pm](https://cloud.githubusercontent.com/assets/45213/11013245/8dd243dc-84b9-11e5-8b69-f0db88c7d7cf.png)

**Comment by evgenii** [comment] 2015-12-04 08:31
Yes, guys this is the problem.
Why are you doing that: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/validators/attachment_size_validator.rb#L29

Currently I've add after_filter in my model for remove duplicates, but this is not a good approach

**Comment by tute** [comment] 2016-03-24 05:06
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1367. Thank you!

**Closed by tute** 2016-03-24 05:06 UTC
