### ISSUE TITLE
Default URL does not return if data exists in paperclip columns

### ISSUE THREAD

**Issue by danieljacobarcher** [thoughtbot/paperclip#1707] opened 2014-11-21 23:59 UTC
Say I have an Avatar and set the `avatar_file_name` `avatar_content_type` `avatar_file_size` to have data in them, but the avatar has not actually been processed or uploaded through Paperclip, Paperclip will still interpolate a URL based on the data.

If I call, `avatar.exists?` It comes back as false.

This was not the case when using Fog, but it arose using Paperclip's S3 adapter. Suggestions?

**Comment by tute** [comment] 2015-05-29 03:05
@danieljacobarcher why do you have `avatar_file_name`, `avatar_content_type` and `avatar_file_size` if file is not uploaded? Who sets those values?

**Comment by jyurek** [comment] 2015-05-29 12:30
@danieljacobarcher In order to have `url` do that, it would have to query the storage backend. This may mean a very costly hit to S3 to determine if the file exists. The performance of having even one url on a page would be abysmal. The whole point of the columns is to keep information locally so we can know about the attachment without having to hit the storage engine. Calling `avatar.exists?` does actually hit S3, so if you need to determine if the file is present in the storage engine you should use that. If the behavior is different between S3 and fog then that is a bug, IMHO, not the fact that a url will generate given all its info.

If you want to submit a new issue or PR about the S3/fog disparity, please do, but I'll be closing this as the reported problem is not a bug and will not be changed. Thank you.

**Closed by jyurek** 2015-05-29 12:30 UTC
