### ISSUE TITLE
"Attachment downloaded from a URL"  and RailsAdmin

### ISSUE THREAD

**Issue by AndreiMotinga** [thoughtbot/paperclip#2104] opened 2016-02-06 22:26 UTC
I was trying to add image to my model with remote url via Rails admin. 
So I added this code 
```
class User < ActiveRecord::Base
  attr_reader :avatar_remote_url
  has_attached_file :avatar

  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end
end
```

Then I added avatar_remote_url  to the model so that RailsAdmin can pick it up with 
```
class AddAvatarRemoteUrlToUsers < ActiveRecord::Migration
  def change
    add_column :users, :avatar_remote_url, :string
  end
end
```

At this point I can't upload image. it says 
```
Paperclip::Errors::MissingRequiredValidatorError
```
So I added 
```
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
```
to the model so now it looks like 
```
class User < ActiveRecord::Base
  attr_reader :avatar_remote_url
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end
end
```

At this point I can successfully upload image by giving it a ulr in "Avatar remote url" field in Rails Admin.  However now if I try to edit model   "Avatar remote url" is empty so when I make changes to other attributes and hit save I get 
```
no implicit conversion of URI::Generic into String
```

So I changed above code a bit
```
class User < ActiveRecord::Base
  attr_reader :avatar_remote_url
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def avatar_remote_url=(url_value)
    if url_value.present?
      self.avatar = URI.parse(url_value)
      # Assuming url_value is http://example.com/photos/face.png
      # avatar_file_name == "face.png"
      # avatar_content_type == "image/png"
      @avatar_remote_url = url_value
    end
  end
end
```

Works for me. 

I'm not sure how relevant this is - and it's probably not the best fix.  I just thought is worth mentioning

**Comment by sikachu** [comment] 2016-02-08 16:31
I think that's a good fix, and I think that's what you actually have to do to handle form input.

This is happening because Rails does not perform blank value rejection for you if it's not a database column. Since you have your own setter, you will have to deal with that yourself.

I'm going to close this issue, as that is the expected behavior.

**Closed by sikachu** 2016-02-08 16:31 UTC
Labels: Question/Discussion
