### ISSUE TITLE
cannot upload pdf file - error content type

### ISSUE THREAD

**Issue by fmh** [thoughtbot/paperclip#1760] opened 2015-02-01 18:26 UTC
Hi,
I can't upload PDF files, i can all others files type but when try pdf, i have a validation type error :  
Document failed to be updated
- Attachment content type is invalid
- Attachment is invalid
```ruby
validates_attachment :attachment, presence: true,
       content_type: {content_type: ['text/plain',
        "application/pdf",               
                                      "application/vnd.ms-excel",
                                      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                      "application/msword",
                                      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]},
                       size: {less_than: 2.megabytes}
````
Ruby : 2.1
Rails : 4.2
Paperclip: 4.2.1
OS X 10.10 with gs

**Comment by hnq90** [comment] 2015-02-05 04:37
I have problem with validation too, so I disable it temporarily by this:
`do_not_validate_attachment_file_type`

**Comment by fmh** [comment] 2015-02-05 07:54
the problem it's only with pdf file

**Comment by imorcott** [comment] 2015-02-18 00:34
I am having the same problem with pdf files.

I posted a work-around that remaps the mime type for pdf: https://github.com/thoughtbot/paperclip/issues/1771

**Comment by tute** [comment] 2015-05-20 04:15
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1771. Thanks for reporting.

**Closed by tute** 2015-05-20 04:15 UTC

**Comment by SmileDMiao** [comment] 2016-11-18 09:05
just add the conotent_type to validate methods,the params in controller show the content_type,i have the problem and solve by it
