### ISSUE TITLE
Iphone portrait pictures are saved as landscape

### ISSUE THREAD

**Issue by aklintsevich** [thoughtbot/paperclip#2035] opened 2015-11-02 02:53 UTC
The : original picture is saved as landscape if it is in portrait mode. All other style pictures show up as portrait which is great, however , this issue messes up the dimensions when an image needs to be cropped.

**Comment by tute** [comment] 2016-03-24 05:21
Thanks for reporting! Closing as duplicate of: https://github.com/thoughtbot/paperclip/issues/1950. Thanks!

**Closed by tute** 2016-03-24 05:21 UTC

**Comment by amanpoplify** [comment] 2017-11-17 08:27
Thumb get auto rotate when video record form iPhone in portrait mode using paperclip-av transcoder
