### ISSUE TITLE
Paperclip does not propagate errors correctly

### ISSUE THREAD

**Issue by DelvarWorld** [thoughtbot/paperclip#1682] opened 2014-10-28 19:22 UTC
See https://github.com/thoughtbot/paperclip/issues/1681

When passing in a valid image, the only error given is: Paperclip::Errors::MissingRequiredValidatorError. It does not give any indication as to what is actually missing.

**Comment by tute** [comment] 2015-05-16 15:26
Thanks! Will close as duplicate of https://github.com/thoughtbot/paperclip/issues/1681, and add a comment there for the error messages that should be improved. Thanks for your input.

**Closed by tute** 2015-05-16 15:26 UTC
