### ISSUE TITLE
Content Type Spoof for pdf on firefox

### ISSUE THREAD

**Issue by donapieppo** [thoughtbot/paperclip#2029] opened 2015-10-19 10:47 UTC
In order to upload pdf from firefox I had to configure 
`Paperclip.options[:content_type_mappings] = { pdf: [ "application/pdf", "binary/octet-stream" ] }`
since firefox sends binary/octet-stream in the header for pdf files.

This is probably an error in firefox but I don't understand why paperclip checks browser hearders in order to find spoofing. 
Is not enought to check extension and the result of `file --mime` (which paperclib already does)?
Why consider a "spoofable" information from the client in order to find spoofing?

**Comment by maclover7** [comment] 2015-10-22 21:22
I'm thinking this might be a bug with Firefox (maybe open up a ticket with them?), but thanks for reporting this. @jyurek, do we check both (or one) of browser headers or `file --mime` when getting a file's mime type? Thanks for reporting this, @donapieppo!

**Comment by donapieppo** [comment] 2015-10-23 09:06
My question was more about the reason of checking browser hearders than this particular bug. 
If the browser send a header for a binary/octet-stream and a file with pdf extension and `file --mime`
confirms it is a pdf, why not discard the header information?
The user wanted to send a pdf and it was a pdf, there was no real spoof except for the browser mistake.

It's easier to debug a `file --mime` error in attributing mime-type to a file than to relay on the browser header.

**Comment by tom-kuca** [comment] 2015-10-26 10:48
There is already a [ticket](: https://bugzilla.mozilla.org/show_bug.cgi?id=373621#c5) at bugzilla, soon we will celebrate 8 years of its existence. There is also a workaround (edit settings in a file in firefox profile), but it's not reliable, the settings are eventually overriden to bad values.

**Comment by tute** [comment] 2016-05-09 21:23
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1771. Thanks for your input.

**Closed by tute** 2016-05-09 21:23 UTC
Labels: Bug, Spoof related or Mime types
