### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by acandael** [thoughtbot/paperclip#2222] opened 2016-06-05 11:08 UTC
Hi,

I'm using paperclip 5.0.0.beta2 in my latest rails (4.2.6) project. The application is hosted on Heroku. I can upload an image and it seems to be stored in a bucket on Amazon S3. However in the browser the image appears to have a broken url, although it's point to the bucket on Amazon S3, the url is:

http://s3.amazonaws.com/gigbnb/profiles/profile_pics/000/000/002/small/anthony_candaele-300x300.jpg?1464956858

When I enter this url in the browser, I  get an xml page with this error message:

    The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

It looks like there is an issue with the S3 endpoint.

However I set the region (eu-west-1) in configuration file:

    config/environments/production.rb

    
    config.paperclip_defaults = {
       storage: :s3,
       s3_region: ENV.fetch('AWS_REGION'),
       s3_credentials: {
         bucket: ENV.fetch('S3_BUCKET_NAME'),
         access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
         secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
       }
    }

My Github repository is at:

https://github.com/acandael/gigbnb

Does anyone have an idea what's going on?

Thanks for your help,

Anthony

**Comment by theonlyrao** [comment] 2016-06-12 03:52
Hi @acandael - check out this issue https://github.com/thoughtbot/paperclip/issues/2025

If you are having the same problem I was, then the image helper is generating a url like `http://s3.amazon.com/my-bucket/...` when it needs to be `http://my-bucket.s3.amazon.com/...`

If that's your issue, then hopefully that other issue will do the trick for you like it did for me.

**Comment by acandael** [comment] 2016-06-15 11:18
Hi @theonlyrao , I used the workaround proposed by animariana in this thread:

https://github.com/thoughtbot/paperclip/issues/2151

that fixed it.

**Comment by sydneyitguy** [comment] 2016-07-19 05:17
I am using 5.0.0 and have the same issue. (I set my `s3_region` correctly to `us-west-2`)

I tried
```
config.paperclip_defaults = { s3_host_name: "s3-#{ENV['AWS_REGION']}.amazonaws.com" } 
```
but that didn't work for me.

I also tried 
```
url: ":s3_domain_url"
```

and became even worse with
```
Paperclip::Errors::InfiniteInterpolationError: Paperclip::Errors::InfiniteInterpolationError
```
for every request.

I had no problem with paperclip < 5.0 and aws-sdk < 2.0 before, and those problems happened after I updated to 

paperclip 5.0.0 and aws-sdk 2.3.22

**Comment by sydneyitguy** [comment] 2016-07-19 06:51
ok.. seems like the `us-east-1` region has some problem with host_name settings
as it has a non-standarized host name like
```
s3.amazonaws.com
s3-external-1.amazonaws.com
```
according to http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.

I tried put those values in my host_name settings, but that didn't work. (retrieving files has no problem, but it give me
```
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```
error when I tried to upload.

I finally had to migrate all my files from `us-east-1` to `us-west-2` and everything works fine now.

**Comment by tute** [comment] 2016-08-16 04:35
As this is not a bug within paperclip, I will close this issue. If you think we can improve documentation, please do send a PR improving the README or improving the wiki, and I'll happily review and merge. Thank you all for reporting and triaging!

**Closed by tute** 2016-08-16 04:35 UTC

**Comment by joshRpowell** [comment] 2016-12-07 17:23
@sydneyitguy I'm having the same issue you had after upgrading to 5.0 and aws-sdk 2.6.  
In development with a newly created bucket I get urls with a region:
![region](https://cloud.githubusercontent.com/assets/6732638/20978545/420fb690-bc77-11e6-91fb-0b7e4b5239e9.png)

However, in staging with a pre-existing bucket my urls do not have a region:
![no_region](https://cloud.githubusercontent.com/assets/6732638/20978546/42136628-bc77-11e6-80ca-c71d7ae006cd.png)

When I use the pre-existing bucket (missing region in url) and specify 
`Paperclip::Attachment.default_options[:s3_host_name] = 's3-us-west-2.amazonaws.com'`

I get the same error you experienced: 
'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.'

I'm thinking migrating production files to new buckets will do the trick as well.  

Curious, how you were able to handle?

**Comment by aditya9026** [comment] 2017-09-16 08:46
useing paperclip 5 and aws-sdk 2.6.0, got stuck nothing works.  

`  has_attached_file :image,
  					styles: { medium: "300x300>", thumb: "100x100>" },
  					# default_url: "/images/missing.png",
			  		storage: :s3,
			        s3_credentials: { access_key_id: "xxxxxx", secret_access_key: "xxxx+xxxx", bucket: "xxxxxx"},
			        s3_region: "us-east-2",
			        path: "Statement/:attactment/:id/:style/:filename",
			        url: ":s3_domain_url",
			        s3_host_name: "s3-us-east-2.amazonaws.com",
			        use_accelerate_endpoint: false
`

**Comment by Lucbug** [comment] 2018-01-21 21:47
Also had to deal with the region in my code not matching the exact region used in AWS S3.

You can check by using the aws-shell and `aws s3api get-bucket-location --bucket yourbucketname`
