### ISSUE TITLE
Interpolations order

### ISSUE THREAD

**Issue by kurapatijayaram** [thoughtbot/paperclip#1836] opened 2015-04-20 19:57 UTC
Hi,
    I am facing one small issue with interpolations order. I had created one interpolation which again has some other interpolations ....
For ex:
Here is my list of paperclip interpolations:
[:attachment, :basename, :class, :content_type_extension, :dotextension, :extension, :filename, :fingerprint, :hash, :id, :id_partition, :param, :rails_env, :rails_root, :style, :tenant_name, :timestamp, :updated_at, :url]

After creating my interpolation(image_path) the list was :
[:attachment, :basename, :class, :content_type_extension, :dotextension, :extension, :filename, :fingerprint, :hash, :id, :id_partition, :img_path,  :param, :rails_env, :rails_root, :style, :tenant_name, :timestamp, :updated_at, :url]

In image_path I am using some interpolations like :rails_root, :tenant_name, :base_name, :extension

My interpolation is in the middle and paperclip is injecting all those in a reverse order
i.e., :image_path will return ":rails_root/:tenant_name/themes/test/:basename.:extension"
Paperclip will loop the interpolations list in the reverse order (:url, :updated_at, :timestamp, :tenant_name, :style, :rails_root, :rails_env, :param, :img_url, :img_path, :id_partition, :id, :hash, :fingerprint, :filename, :extension, :dotextension, :content_type_extension, :class, :basename, :attachment)
 so it is unable to inject :rails_root and :tenant_name because it was looped before image_path was injected....

How to handle this ?

Correct me if I am wrong.
Thank u :-)

**Comment by kurapatijayaram** [comment] 2015-04-20 19:59
If i change the order its working but I dont think that is the right way to handle this situation ...

**Comment by jyurek** [comment] 2015-04-20 19:59
I would recommend not nesting interpolations. That is, don't put `:rails_root` inside `:img_path`.

**Comment by kurapatijayaram** [comment] 2015-04-20 20:02
hi @jyurek  thanks for the reply ....
Then how to achieve dynamic urls/paths ??

**Comment by jyurek** [comment] 2015-04-20 20:14
What is it you're trying to achieve? You should just be able to put the dynamic part into the `:img_path` interpolation.

**Comment by kurapatijayaram** [comment] 2015-04-20 20:22
I have defined that particular interpolation in one class and user will mention his own path to save the attachment using the instance variable of that class ... So that I can use same class wherever file uploading is required .

**Comment by jyurek** [comment] 2015-04-20 20:30
I'm not 100% sure I follow, but based on what you said, you could have the interpolation call a method on the object. That method could either return your default (which would be `Rails.root`, it sounds like) or the user's overridden path.

**Comment by kurapatijayaram** [comment] 2015-04-20 20:32
User will use existing and new interpolations

**Comment by kurapatijayaram** [comment] 2015-04-20 20:33
Whole path will be decided dynamically ...

**Comment by jyurek** [comment] 2015-04-21 13:56
I would recommend structuring your setup so that doesn't need to happen, but if you can't, then I would recommend that you don't use interpolations for this. The `:path` option can take a lambda. This lambda will be executed and the result will be interpolated. You can add dynamic elements there.

**Comment by tute** [comment] 2015-05-20 03:20
Closing this issue as it's not a bug in paperclip; please feel free to continue discussion or reopen if it is actually an issue in paperclip's codebase. Thank you!

**Closed by tute** 2015-05-20 03:20 UTC
