### ISSUE TITLE
Incorrectly Receiving Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by Undistraction** [thoughtbot/paperclip#1342] opened 2013-09-19 09:47 UTC
So far as I understand it, this error pertains to Paperclip being unable to find `identify`, however I am receiving it during validation only for a specific PDF, with other PDFs being successfully handled, so it appears this error is incorrect. The PDF appears to be fine and comes from the same source as all the other PDFs which are handled correctly.

Attachment setup:

```
has_attached_file :attachment,
    path: "downloads/:basename_:style.:extension",
    url: "downloads/:basename_:style.:extension",
    s3_host_name: ENV["AWS_REGION"],
    styles: { thumb: ['80x80#', :png] },
    s3_headers: {
      'Cache-Control' => 'max-age=29030400'
    }
```

My validations:

```
validates_attachment_presence :attachment, message: "No file was selected"
validates_attachment_content_type :attachment, content_type: "application/pdf", message: "Only PDFs are allowed"
```

I can reproduce using the Paperclip Demo which gives me:

```
3 errors prohibited this friend from being saved:

Avatar Paperclip::Errors::NotIdentifiedByImageMagickError
Avatar Paperclip::Errors::NotIdentifiedByImageMagickError
Avatar Paperclip::Errors::NotIdentifiedByImageMagickError
```

I'd be happy to send the PDF directly if that would be of use.

**Comment by maclover7** [comment] 2015-03-09 22:09
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by JoelBeasley** [comment] 2015-04-01 16:53
@maclover7 This is still an issue for me, some PDFs simply do not work and throw the error, others are fine.

**Comment by maclover7** [comment] 2015-04-09 23:58
@JoelBeasley, since this is from a few years ago, what version of paperclip are you on right now?

**Comment by tute** [comment] 2015-05-25 15:45
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1223.

**Closed by tute** 2015-05-25 15:45 UTC
