### ISSUE TITLE
Paperclip clears association. Can't load dynamic styles through the association model

### ISSUE THREAD

**Issue by leosmeira** [thoughtbot/paperclip#2233] opened 2016-06-17 03:20 UTC
I need to access association model to get dynamic styles, but I can't access site_id attribute on instance.

Error: undefined method `styles' for nil:NilClass

- Ruby 2.3
- Rails 4.2.6
- Paperclip 4.3.6

Controller:
```ruby
def create
  @site = Site.find(params[:site_id])
  @banner = @site.banners.new(banner_params)
  @banner.save
  respond_with(@banner)
end
```

Model:
```ruby
  belongs_to :site
  has_attached_file :imagem,         
            :styles => lambda { |file| eval(file.instance.site.styles) },
            :url => "/banners/:id/:style_:basename.:extension",
            :path => ":rails_root/public/banners/:id/:style_:basename.:extension",
```

**Comment by evseevleo** [comment] 2016-07-22 10:22
I have the same problem
* Ruby 2.1.4
* Rails 4.1.8
* Paperclip 4.2.4

Don't know if it's sufficient in your case, but you can try ```file.instance.reload.site.styles``` instead of ```file.instance.site.styles```

**Comment by tute** [comment] 2016-08-19 02:03
@leosmeira, does @evseevleo's comment fix your issue? Closing as this is not a bug in paperclip, but happy to continue further discussion. Thanks!

**Closed by tute** 2016-08-19 02:03 UTC
