### ISSUE TITLE
[IGNORE] Actual Issues

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1806] opened 2015-03-09 22:22 UTC
Just a place for me to keep track of issues and feature requests that are for reals. Please ignore this issue.

# Issues/Bugs
- #1040 
- #1352 
- #1361 
- #1561 
- #1564 
- #1574 
- #1764 
- #1848

# Feature Requests
- #1129 
- #1462 / #1479 / #1506 / #1523 / #1601 / #1637 

# Pull Requests (Ready to Merge)
- #1467 
- #1655 
- #1708

**Comment by jyurek** [comment] 2015-03-13 16:28
Thanks for doing this, @maclover7.

**Comment by tute** [comment] 2015-05-09 18:33
@maclover7 this is great! Thank you! :+1:

**Comment by tute** [comment] 2015-05-12 02:30
@maclover7 will close this as it's not a bug, but obviously feel free to continue linking to it and using it as your personal notes. Thanks!

**Closed by tute** 2015-05-12 02:30 UTC

**Comment by maclover7** [comment] 2015-05-12 17:49
No problem. :+1:
