### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError for XLS file

### ISSUE THREAD

**Issue by heaven** [thoughtbot/paperclip#1678] opened 2014-10-22 15:32 UTC
It does work properly from the rails console:
```ruby
Source.create!({ :name => "source name", :status => Source::STATUSES.values.sample, :source => File.open("spec/files/Import-v1.6.0.xls") }, :without_protection => true)
```
Which issues the next commands:
```
Command :: file -b --mime 'spec/files/Import-v1.6.0.xls'
Command :: file -b --mime '/tmp/5bbaf05a749ce8a09b649e9955a86f3720141022-17953-rbbbd5.xls'
Command :: file -b --mime '/tmp/5bbaf05a749ce8a09b649e9955a86f3720141022-17953-1t302kh.xls'
 => #<Source id: 1, name: "source name", ...
```

But causes problems in my specs. and what is weird is that if I run a single spec file, like `rspec spec/models/delayed_job_spec.rb` it does work, but if I run all specs by `rspec spec/models` a particular case always fails at this place:
```ruby
src = FactoryGirl.create(:source, :source => File.open("spec/files/Import-v1.6.0.xls"))
```
Tried to use debugger (byebug) and run that command manually as well as the same one I tried from the rails console. They both fail. Another issue with this is that it does not use the `file` command but `identify` instead, and fails with the next error:
```
ActiveRecord::RecordInvalid Exception: Validation failed: Source Paperclip::Errors::NotIdentifiedByImageMagickError, Source Paperclip::Errors::NotIdentifiedByImageMagickError
```

Worth to mention it doesn't fail instantly, before it tries to run `soffice` (from the openoffice package):
![screenshot 859](https://cloud.githubusercontent.com/assets/126732/4738897/63897e9a-5a00-11e4-9b07-b99dea11e535.png)

Does it try to make a thumbnail for the attachment? I didn't requested so, I mean in the model I do not have styles defined for this attachment.

What do i do wrong?

**Comment by tute** [comment] 2015-05-25 15:45
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1223.

**Closed by tute** 2015-05-25 15:45 UTC
