### ISSUE TITLE
While refreshing original file is touched

### ISSUE THREAD

**Issue by dmitry** [thoughtbot/paperclip#1756] opened 2015-01-28 15:31 UTC
While refresh rake task the original file is touched, even if it's not in `STYLES` list. That because it's added here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L426 and not removed while flushing here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/filesystem.rb#L37

It should removed from before flushing, when it's not selected for update.

**Comment by tute** [comment] 2015-05-20 04:17
Can you please explain further the issue? Would you submit a PR to discuss over concrete code? Thank you!

**Comment by dmitry** [comment] 2015-05-20 11:32
@tute original style always being rewritten when using the refresh styles, even if no original style were listed. I will try to find out a time to include test code in PR soon.

**Comment by dmitry** [comment] 2015-05-27 12:11
Similar issue: https://github.com/thoughtbot/paperclip/issues/1804

**Comment by tute** [comment] 2015-05-27 13:54
Thanks for reporting and the link, @dmitry. Closing this issue as a duplicate of: https://github.com/thoughtbot/paperclip/issues/1804.

**Closed by tute** 2015-05-27 13:54 UTC
Labels: More info needed
