### ISSUE TITLE
Force remove files from the filesystem

### ISSUE THREAD

**Issue by USvER** [thoughtbot/paperclip#1443] opened 2014-02-17 05:50 UTC
I want to manage destruction of files manualy.
I'm configured paperclip to not remove files automaticaly
```ruby
:preserve_files => true
```

But how do i remove files now?
```ruby
@asset.file.clear
```
Does not removing files, i guess because of my configuration, but how do force deletion?

**Comment by maclover7** [comment] 2015-03-09 22:35
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by MoustafaEid** [comment] 2015-03-09 23:18
To be honest I don't think it's an issue, there's simply no way in paperclip to manually remove the file on demand, at least to my knowledge.
My use case is that I wanted to upload files to S3 via paperclip, but then run a scheduled job that cleans up files that haven't been updated for more than week.
Hope this helps.

**Comment by maclover7** [comment] 2015-03-09 23:36
Sounds like a problem for DelayedJob to solve. Is it okay if this issue is closed? @MoustafaEid

**Comment by MoustafaEid** [comment] 2015-03-10 00:07
@maclover7 even if I use DelayedJob (or even the console, but regardless), how can I force paperclip to delete the attached file?

**Comment by maclover7** [comment] 2015-03-10 00:08
Oh, you're right -- sounds like an AWS issue. Is it alright if this issue is closed?

**Comment by MoustafaEid** [comment] 2015-03-10 00:13
Well, but if we abstract the storage used (S3, file system etc..), wouldn't it make sense for paperclip to provide something like `@photo.image.clear`? So if you end up switching the storage used, or even if you don't use S3, you can rely on paperclip to abstract for you.

Just brainstorming here, all opinions are welcome :)

**Comment by maclover7** [comment] 2015-03-10 00:14
Interesting concept; would you be willing to send in a PR to solve the problem?

**Comment by MoustafaEid** [comment] 2015-03-10 00:20
I would love to, but I don't have the time :) I guess if @USvER doesn't need this anymore this issue can be closed.

**Comment by vigneshacker** [comment] 2015-03-10 02:58
Please explain. How to do this. How to manually delete file if we use paranoia for soft deleting.

**Comment by USvER** [comment] 2015-03-10 10:16
Hi,
I still didn't cleaned my files... My project is small... But it is getting bigger and bigger... 22 GB of files for now...
I'm looking for a solution, i guess i would need to create rake task for this...

**Comment by vigneshacker** [comment] 2015-03-10 11:24
Is there any way like @MoustafaEid  told. Please share it.

**Comment by USvER** [comment] 2015-03-10 16:25
Let me clarify the issue. There is no fine-grain control of file deletion. 
You can define deletion strategy for the whole collection but not for individual files.
There is many use-cases when you want a per-entry deletion control.

So there should be some option to force file deletion if `preserve_files: "true"` is defined, and maybe the option to preserve file when it's `false`.

Because there is no such option i was forced to delete db entries without deleting files in all cases. And now i have other issue: how do I delete files that is not used anymore?
Because my project is small (~20GB of files) it's ok... But still this issue should be addressed...

**Comment by MoustafaEid** [comment] 2015-03-10 16:49
to add to @USvER's point, AFAIK, there is no way currently to retrieve the original file path if S3 storage is being used, maybe if we have the file path we can manually delete.

**Comment by tute** [comment] 2015-05-13 05:52
How should we deal with this issue @jyurek ?

**Comment by tute** [comment] 2016-05-10 20:37
I am able to remove filesystem files with the following snippet in https://github.com/thoughtbot/paperclip_demo:

```ruby
friend = Friend.last
(friend.avatar.styles.keys + [:original]).each do |style|
  file_name = friend.avatar.url(style).split("?").first
  file_path = Rails.root.
    join("public").
    join(file_name.gsub(/^\//, ""))

  if File.exist?(file_path)
    FileUtils.rm(file_path)
    print "."
  else
    puts "ERROR: #{file_path} not found"
  end
end
```

This will remove only current styles (and original, which you might or might not want to do). You can also iterate on the directory structure differently to make sure you cleanup everything.

If you think it's useful, we might add this to paperclip's wiki.

Closing the issue as it's not a bug in paperclip. Happy to continue further discussion.

**Closed by tute** 2016-05-10 20:37 UTC
