### ISSUE TITLE
Spoofing detection issue

### ISSUE THREAD

**Issue by gregmolnar** [thoughtbot/paperclip#1574] opened 2014-06-16 13:41 UTC
I am trying to convert a pdf to a jpg but I am getting a spoofing error. For some reason at this line: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/validators/media_type_spoof_detection_validator.rb#L8 the `original_filename` still has the pdf extension hence the spoofing error. 
I tried to write a test to prove the issue but I am getting loads of errors when trying to run the tests. There is a dependency issue with bourne and mocha first of all. When I got around that there are still loads of random failures.

**Comment by maclover7** [comment] 2015-03-10 00:30
Hi @gregmolnar and @mreinsch ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by mreinsch** [comment] 2015-03-11 21:57
this isn't fixed yet, no. I still need the following workaround:

```
module Paperclip
  class MediaTypeSpoofDetector

    def spoofed_with_pdf_conversion_fix?
      return false if calculated_content_type == "image/jpeg"
      spoofed_without_pdf_conversion_fix?
    end

    alias_method_chain :spoofed?, :pdf_conversion_fix
  end
end
```

The code that I posted hasn't really changed. It's triggered when you try and upload a pdf and the pdf is converted into a jpeg (as instructed).

**Comment by gregmolnar** [comment] 2015-03-12 06:08
@mreinsch I am not working on the project anymore where I had this issue and I can't remember what was my workaround.

**Comment by maclover7** [comment] 2015-03-12 21:54
Would you be willing to send in a PR to solve the problem? Thanks!

**Comment by mreinsch** [comment] 2015-03-12 23:10
@maclover7 the patch I have is just a workaround, the actual issue looks to be quite a bit deeper. I'm not sure I'll be able to find the time to address this properly.

**Comment by tute** [comment] 2016-05-10 22:03
How can we replicate this issue, in order to attempt a fix? Thanks!

**Comment by bouchard** [comment] 2016-08-01 00:18
@tute, I've recently run into this issue. It appears to happen if `:original` has a filetype specified. For example:

```ruby
class Document
  has_attached_file :asset,
      styles: { original: ['1920x1920>', :jpg] }
  validates_attachment :asset,
    content_type: { content_type: ['image/jpeg', 'image/png', 'application/pdf'] }
end
```

`Document.create(asset: File.open('example.pdf'))` will give the error:

[paperclip] Content Type Spoof: Filename 1.pdf (application/pdf from Headers, ["application/pdf"] from Extension), content type discovered from file command: image/jpeg. See documentation to allow this combination.

**Comment by ifokeev** [comment] 2016-08-04 22:14
@bouchard in my case it was because I have no "file" library.
I found it here: 
https://github.com/thoughtbot/paperclip/blob/e60f00027704298455c039e111d96bcf46e12822/lib/paperclip/media_type_spoof_detector.rb#L75

The lib: https://pkgs.alpinelinux.org/package/edge/main/armhf/file

**Comment by tute** [comment] 2016-08-05 14:41
> @bouchard in my case it was because I have no "file" library.

This one is specified in the dependencies section: https://github.com/thoughtbot/paperclip#file. @bouchard is that your issue? Or are those the steps to reproduce on any system?

**Comment by bouchard** [comment] 2016-08-05 15:16
Hello @tute,

I'm on OS X, so `file` isn't an issue.

I've confirmed that my snippet above is a minimal test case that reproduces the issue with Paperclip 5.0.0.

```bash
rails new test_app
cd test_app
echo "gem 'paperclip'" >> Gemfile
bundle install
rails g model Document
vi app/models/document.rb
# class Document
#   has_attached_file :asset,
#       styles: { original: ['1920x1920>', :jpg] }
#   validates_attachment :asset,
#     content_type: { content_type: ['image/jpeg', 'image/png', 'application/pdf'] }
# end
rails console
> d = Document.new
=> #<Document id: nil, asset_file_name: nil, asset_content_type: nil, asset_file_size: nil, asset_updated_at: nil, created_at: nil, updated_at: nil>
irb(main):002:0> d.asset = File.open('any_pdf_to_test_with.pdf')
Command :: file -b --mime '/var/folders/xx/f61kmnqd013bk598qss8l9_w0000gn/T/5fe0bdbbc39578617959a974b8ad823920160805-20861-16aw80p.pdf'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/xx/f61kmnqd013bk598qss8l9_w0000gn/T/5fe0bdbbc39578617959a974b8ad823920160805-20861-15q9gk8.pdf[0]' 2>/dev/null
Command :: convert '/var/folders/xx/f61kmnqd013bk598qss8l9_w0000gn/T/5fe0bdbbc39578617959a974b8ad823920160805-20861-15q9gk8.pdf[0]' -auto-orient -resize "1920x1920>" '/var/folders/xx/f61kmnqd013bk598qss8l9_w0000gn/T/fa5987387fddf624f6d24b19ffcc326f20160805-20861-1khzdbg.jpg'
=> #<File:/Users/brady/any_pdf_to_test_with.pdf>
irb(main):003:0> d.save
   (0.2ms)  begin transaction
Command :: file -b --mime '/var/folders/xx/f61kmnqd013bk598qss8l9_w0000gn/T/5fe0bdbbc39578617959a974b8ad823920160805-20861-ks3fu0.pdf'
[paperclip] Content Type Spoof: Filename any_pdf_to_test_with.pdf (application/pdf from Headers, ["application/pdf"] from Extension), content type discovered from file command: image/jpeg. See documentation to allow this combination.
   (0.1ms)  rollback transaction
=> false
```

**Comment by bouchard** [comment] 2016-08-22 17:11
Adapted fix for Rails 5 (`alias_method_chain` has gone away):

```ruby
module MediaTypeSpoofDetectorFix
  def spoofed?
    return false if calculated_content_type == 'image/jpeg'
    super
  end
end

module Paperclip
  class MediaTypeSpoofDetector
    prepend MediaTypeSpoofDetectorFix
  end
end
```

**Comment by mike-burns** [comment] 2018-04-27 20:17
Looks like we found a workaround, closing.

**Closed by mike-burns** 2018-04-27 20:17 UTC
Labels: Spoof related or Mime types
