### ISSUE TITLE
Multiple geometry flags

### ISSUE THREAD

**Issue by alassek** [thoughtbot/paperclip#1851] opened 2015-05-12 07:31 UTC
I'm creating a style for use on mobile devices. Since photos on a mobile device can be either landscape or portrait, I don't want to set a maximum width or height because either one or the other will get sized down too far.

Constraining the image by a maximum pixel count seems like the appropriate solution to this problem, so I initially set my geometry to `2073600@`.

Unfortunately, this leads to images that are smaller than the maximum being _upscaled_ which I definitely don't want. According to the [ImageMagick documentation][0], I should instead use `2073600@>`. This works fine from the command line.

However, it appears that Paperclip ignores anything other than the first flag in a geometry string. (I updated to 4.2.1 to make sure this wasn't added later)

So then I tried:

```ruby
mobile: { convert_options: "-resize '2073600@>'" } 
```

which causes an exception because geometry is nil. So i then tried this:

```ruby
mobile: { geometry: '', convert_options: "-resize '2073600@>'" }
```

which sort of works, except that mobile styles are just not being processed when they don't require resizing.

I think I've managed to work around this by doing some dynamic geometry based on pixel count:

```ruby
class Attachment < ActiveRecord::Base
  has_attached_file :body, ... , styles: {
    mobile: {
      geometry: ->(a){ a.pixels > 2073600 ? '2073600@' : a.geometry.to_s }
    }
  }

...

  def geometry
    @geometry ||= Paperclip::Geometry.from_file(body.queued_for_write[:original] || body.url)
  rescue Paperclip::Errors::NotIdentifiedByImageMagickError
    nil
  end

  def pixels
    geometry ? geometry.width * geometry.height : 0
  end
end
```

But, boy this seems like an ugly workaround. Was it an intentional choice to ignore multiple flags in the geometry string? Do you have a better suggestion on how to approach this?

  [0]: http://www.imagemagick.org/Usage/resize/#pixel

**Comment by alassek** [comment] 2015-05-12 07:35
In case it matters, my storage strategy is Rackspace CloudFiles using Fog.

**Comment by tute** [comment] 2015-05-29 02:21
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1313. Thanks for your help @alassek! If you can submit a PR that will be VERY appreciated. :)

**Closed by tute** 2015-05-29 02:21 UTC

**Comment by alassek** [comment] 2015-07-27 23:47
@tute this issue has nothing at all to do with #1313 that I can tell, were you doing a search for `NotIdentifiedByImageMagickError`?

**Comment by tute** [comment] 2015-07-28 08:06
I might have made a mistake. I would reopen it, but now we have a shiny PR where to continue the thread! :) Thanks for your work.
