### ISSUE TITLE
NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by djvs** [thoughtbot/paperclip#1860] opened 2015-05-15 16:32 UTC
{"image":["Paperclip::Errors::NotIdentifiedByImageMagickError","Paperclip::Errors::NotIdentifiedByImageMagickError","Paperclip::Errors::NotIdentifiedByImageMagickError"]}

Here's the weird part.  This only occurs when I do @object.update(object_params("update")), for object_params: 

 def object_params(permission)
      params.permit(  .........    , :image,  ........)
end

But it works fine when I do @object.image and @object.save!  So clearly, nothing to do with ImageMagick...

Using neo4j.rb, assuming there's some significant difference with the .update method.

**Comment by jyurek** [comment] 2015-05-15 17:53
Ballparking here: is `object_params` returning what you think it's returning? If you built the form "normally" for example, the `object` value might be a subkey, not a top level key.

**Comment by djvs** [comment] 2015-05-15 17:53
Yes, I dumped it via "inspect" and checked.

**Comment by jyurek** [comment] 2015-05-15 17:56
So what you pasted at the top is what you get from `@object.errors`?

Can you check to see what `@object.image.original_file` returns right before the save? What I'm thinking here is that somehow the image data is getting lost before the save and so ImageMagick is flipping out about not actually having the data.

**Comment by djvs** [comment] 2015-05-15 18:41
Well, no, I can't do that via .update...

**Comment by djvs** [comment] 2015-05-15 18:41
Hold on, going to send this to neo4jrb devs

**Comment by tute** [comment] 2015-05-25 15:44
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1223.

**Closed by tute** 2015-05-25 15:44 UTC
Labels: More info needed
