### ISSUE TITLE
Content type validation works for 'image/*' but not for 'application/pdf'

### ISSUE THREAD

**Issue by imorcott** [thoughtbot/paperclip#1771] opened 2015-02-17 19:19 UTC
When I try to use the content type validation on non-image files, I am getting a validation failed error.  It seems that the validation code is getting a content type of "application/force-download".  
When I run file -b on the file I get:
file -b --mime clinical\ research\ review\ algorithm_updated\ 120109.pdf 
application/pdf; charset=binary

System details are as follows:

I am testing on a Mac with OS version 10.10.2 
running the server locally  with:
WEBrick 1.3.1
ruby 2.1.5 (2014-11-13) [x86_64-darwin14.0]

Gemfile
ruby '2.1.5'
gem 'rails', '~> 4.2.0'
gem "rmagick"
gem "paperclip", "~> 4.2"
gem 'aws-sdk', '~> 1.5.7'

In my model:

  has_attached_file :document
  validates_attachment  :document,
                       :content_type => { :content_type => 'application/pdf' },
                       :size => { :in => 0..MAX_DOC_SIZE }
looking at the params for the create:
@content_type="application/force-download",
 @headers="Content-Disposition: form-data; name=\"document_upload[document]\"; filename=\"clinical research review algorithm_updated 120109.pdf\"\r\nContent-Type: application/force-download\r\n">},

The fun this is that validation works for images. 
Using the model code for images:
has_attached_file :image,
                    :styles => { :thumb => "100x100>" },
                    :convert_options => {
                        :medium => "-quality 80 -interlace Plane",
                        :thumb => "-quality 80 -interlace Plane"
                    }

  validates_attachment :image,
                       :content_type => { :content_type => /\Aimage\/.*\Z/ },
                       :size => { :in => 0..MAX_IMAGE_SIZE }

So for images all is working as expected.  However, for other content types it is not.

Any clues would be appreciated.

Regards,
-Ian

**Comment by imorcott** [comment] 2015-02-18 00:30
My work-around is to associate pdf with "application/force-download".
I added the following two lines to config/initializers/paperclip_init.rb where I have my other configs 

Mime::Type.unregister(:pdf)
Mime::Type.register "application/force-download", :pdf, [], %w(pdf)


Then to allow pdf files you need to add "application/force-download" as an allowed content_type.

validates_attachment  :document,
         :content_type => { :content_type => 'application/force-download' }
 
Why pdf files are having their content_type detected as  'application/force-download' is an open question. However, rather than not supporting pdf files the work-aound above does seem to work.

Finding a solution that does not require remapping the mime types would be better. I am open to a better solution.

**Comment by LucasCioffi** [comment] 2015-02-25 22:34
@imorcott Any suggestions for how to enable common files like .doc, .xls, etc?  Would it look like this?

validates_attachment_content_type :document, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/force-download", "application/xls", "application/xlsx", "application/doc", "application/docx", "application/ppt", "application/pptx"]

Does anything need to be done to the Mime::Types to make that happen?  Thank you!

**Comment by imorcott** [comment] 2015-02-27 03:37
The main issue I think is with rails when downloading pdf files.  The Mime::Type is not returned as 'application:pdf' instead it is:  "application/force-download"
As it is currently, Rails has several Mime:Type that are built in.  It would be great if the list was a bit more comprehensive since spoof detection is used to map extensions to content_type. I have added the following:
Note that I needed to unregister the pdf so I could re-assign it to "application/force-download" do to the file uploading of pdf not correctly getting the content_type correct.

Mime::Type.unregister(:pdf)

octet_stream = MIME::Types["application/octet-stream"].first
octet_stream.extensions << "mts"
MIME::Types.add octet_stream
octet_stream = MIME::Types["application/octet-stream"].first
octet_stream.extensions << "psd"
MIME::Types.add octet_stream


Mime::Type.register "application/force-download", :pdf, [], %w(pdf)
# Mime::Type.register "application/octet-stream", :mts, [], %w(mts)

Mime::Type.register "application/vnd.ms-office", :pot, [], %w(pot)
Mime::Type.register "application/vnd.ms-office", :ppt, [], %w(ppt)
Mime::Type.register "application/vnd.ms-office", :xls, [], %w(xls)
Mime::Type.register "application/vnd.ms-office", :xlt, [], %w(xlt)

Mime::Type.register "text/x-markdown", :md, [], %w(md)
Mime::Type.register "text/html", :mm, [], %w(mm)

Mime::Type.register "application/vnd.oasis.opendocument.presentation", :odp, [], %w(odp)
Mime::Type.register "application/vnd.oasis.opendocument.spreadsheet", :ods, [], %w(ods)

# Microsoft https://technet.microsoft.com/en-us/library/ee309278%28office.12%29.aspx
# http://filext.com/faq/office_mime_types.php
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", :xlsx, [], %w(xlsx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.template", :xltx, [], %w(xltx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.template", :potx, [], %w(potx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.slideshow", :ppsx, [], %w(ppsx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.presentation", :pptx, [], %w(pptx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.slide", :sldx, [], %w(sldx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.wordprocessingml.document", :docx, [], %w(docx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.wordprocessingml.template", :dotx, [], %w(dotx)
Mime::Type.register "application/vnd.ms-excel.addin.macroEnabled.12", :xlam, [], %w(xlam)
Mime::Type.register "application/vnd.ms-excel.sheet.binary.macroEnabled.12", :xlsb, [], %w(xlsb)

Mime::Type.register "application/vnd.ms-word.document.macroEnabled.12", :docm, [], %w(docm)
Mime::Type.register "application/vnd.ms-excel.sheet.macroEnabled.12", :xlsm, [], %w(xlsm)
Mime::Type.register "application/vnd.ms-excel.template.macroEnabled.12", :xltm, [], %w(xltm)
Mime::Type.register "application/vnd.ms-powerpoint.presentation.macroEnabled.12", :pptm, [], %w(pptm)
Mime::Type.register "application/vnd.ms-powerpoint.slideshow.macroEnabled.12", :ppsm, [], %w(ppsm)
Mime::Type.register "application/vnd.ms-powerpoint.template.macroEnabled.12", :potm, [], %w(potm)
Mime::Type.register "application/vnd.ms-powerpoint.addin.macroEnabled.12", :ppam, [], %w(ppam)
Mime::Type.register "application/vnd.ms-powerpoint.slide.macroEnabled.12", :sldm, [], %w(sldm)
Mime::Type.register "application/msonenote", :one, [], %w(one onetoc2 onetmp onepkg)
Mime::Type.register "application/vnd.ms-officetheme", :thmx, [], %w(thmx)
Mime::Type.register "application/msword", :doc, [], %w(doc dot)
Mime::Type.register "application/vnd.ms-word.template.macroEnabled.12", :dotm, [], %w(dotm)

**Comment by orenyk** [comment] 2015-03-10 18:00
This seems related to #1694 to me; I've run into a similar [issue](https://github.com/YaleSTC/reservations/issues/1016) although Firefox is reporting the `content_type` as `application/octet-stream` for pdf files where Chromium is reporting it correctly (both on Fedora 20). Any thoughts on how to address this?

**Comment by cnk** [comment] 2015-03-15 03:05
What I did to work around browsers sending inaccurate mime types with file uploads was to add a "correct the headers" step that was run before assigning the file to my paperclip model. In my specific case, a flash uploader I use sends everything with application/octet-stream as the mime type. So anything that comes in as that, I correct to whatever the unix file command says it is - except that if file says they are zip files, I further correct the type to be the mime type based on the file extension.

This means that if a user uploads a zip file with a MS Office extension, it can really be any damn thing and my mime-spoofing check can't do a thing about it. But that is one of the prices I pay for us using a very old version of RHEL. 

Gist of my workaround code: https://gist.github.com/cnk/4453c6e81837e8d38b7e

**Comment by MrHubble** [comment] 2015-03-19 20:19
@LucasCioffi I was able to get xlsx working by adding

````rb
#config/initializers/mime_types.rb
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", :xlsx, [], %w(xlsx)
Mime::Type.register "application/vnd.ms-office", :xls, [], %w(xls)
````

and then in my model I have:

````rb
validates_attachment_content_type :upload, :content_type  => ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",'application/pdf', /\Aimage\/.*\Z/ ]
````

I hope that helps.

**Comment by ostraperlera** [comment] 2015-05-06 11:07
I  run into the same issue, it seems to be a consequence of #1694 and a bug in Firefox that has been open for quite some time => https://bugzilla.mozilla.org/show_bug.cgi?id=373621

To fix your own browser and continue developing, a workaround might be to reset Firefox settings.

**Comment by pusewicz** [comment] 2016-06-16 13:37
It gets even worse. I have a customer that's uploading PDF files with Firefox 47, and almost all of them are reported as `application/json`. I can't reproduce that though. I think there should be a way to overwrite the content type with the one detected by Paperclip, eg. before validation.

**Comment by 1v** [comment] 2016-10-24 22:18
Can't validate any djvu file:
```
  validates_attachment_content_type :file, content_type: /\A(application\/pdf|image\/vnd\.djvu)\z/
```
```
[paperclip] Trying to link public/1.djvu to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-1eonqd8.djvu
[paperclip] Trying to link /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-1eonqd8.djvu to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-t8i6dm.djvu
Command :: file -b --mime '/tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-t8i6dm.djvu'
"image/vnd.djvu; charset=binary\n"
"image/vnd.djvu"
   (0.1ms)  BEGIN
[paperclip] Trying to link /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-1eonqd8.djvu to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-z5s1o1.djvu
Command :: file -b --mime '/tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-z5s1o1.djvu'
"image/vnd.djvu; charset=binary\n"
"image/vnd.djvu"
   (0.1ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: File content type is invalid, File is invalid
```
But pdf is ok:
```
[paperclip] Trying to link public/1.pdf to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-fnwkx1.pdf
[paperclip] Trying to link /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-fnwkx1.pdf to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-hvvykg.pdf
Command :: file -b --mime '/tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-hvvykg.pdf'
"application/pdf; charset=binary\n"
"application/pdf"
   (0.2ms)  BEGIN
[paperclip] Trying to link /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-fnwkx1.pdf to /tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-1xo1sb4.pdf
Command :: file -b --mime '/tmp/c4ca4238a0b923820dcc509a6f75849b20161024-28930-1xo1sb4.pdf'
"application/pdf; charset=binary\n"
"application/pdf"
  SQL (0.6ms)  INSERT INTO
```
File: https://upload.wikimedia.org/wikipedia/commons/2/29/Alice_in_Wonderland.djvu

**Comment by 1v** [comment] 2016-10-25 10:41
Real content type was `image/vnd.djvu+multipage`.

**Comment by jaimerodas** [comment] 2016-12-16 22:50
@1v how did you figure out the content type?

**Comment by 1v** [comment] 2016-12-17 05:22
@jaimerodas don't remember, maybe with my fork https://github.com/thoughtbot/paperclip/compare/master...1v:master

**Comment by leder11011** [comment] 2017-01-23 11:58
Using paperclip v5.1.0 on ubuntu 16.04...
My validation of jar file does not work, whatever browser I use chromium or firefox:
`validates_attachment :attachment, content_type: { content_type: 'application/java-archive'}, size: { in: 0..10.megabytes }`

only not validating works:
```
# Explicitly do not validate
  do_not_validate_attachment_file_type :attachment

```
Thanks!
Gerrit

**Comment by alosada** [comment] 2018-01-09 21:40
Any news on this?
I've tried the workarounds here to upload pdf but I'm still not able to. My file content file is reaching the server correctly as 'application/pdf' but I'm still getting invalid. 
even `do_not_validate_attachment_file_type :attachment` is not working

**Comment by edusantana** [comment] 2018-01-15 22:16
I was using:

```
validates_attachment_content_type :anexo, content_type: { content_type: "application/pdf" }
```
Then I changed for:

```
validates_attachment_content_type :anexo, content_type: /.*pdf/
```

And it works now.

**Comment by mike-burns** [comment] 2018-04-27 20:28
Looks like we found a workaround, closing.

**Closed by mike-burns** 2018-04-27 20:28 UTC
Labels: Spoof related or Mime types
