### ISSUE TITLE
InfiniteInterpolation error on model.file.url if file.exists? is false

### ISSUE THREAD

**Issue by vedant1811** [thoughtbot/paperclip#1843] opened 2015-05-01 08:44 UTC
Paperclip seems to be throwing errors where it should be returning `nil`, or atleast, failing with an improper error message.

If a model that `has_attachment :file` returns `false` for `model.file.exists?`, it throws a `Paperclip::Errors::InfiniteInterpolationError` in `model.file.url`

In rails console:

    irb(main):013:0* seller.image.exists?
    => false
then

    irb(main):011:0> seller.image.url
    Paperclip::Errors::InfiniteInterpolationError: Paperclip::Errors::InfiniteInterpolationError
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:53:in `url'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:34:in `block (2 levels) in interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:33:in `gsub'
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:33:in `block in interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `each'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `inject'
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/url_generator.rb:13:in `for'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:143:in `url'
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:54:in `url'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:34:in `block (2 levels) in interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:33:in `gsub'
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:33:in `block in interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `each'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `inject'
    from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/interpolations.rb:32:in `interpolate'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/url_generator.rb:13:in `for'
            from /home/vedant/.gem/ruby/2.2.1/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:143:in `url'
    from (irb):11
    from /home/vedant/.gem/ruby/2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
            from /home/vedant/.gem/ruby/2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
            from /home/vedant/.gem/ruby/2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /home/vedant/.gem/ruby/2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
            from /home/vedant/.gem/ruby/2.2.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
            from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'irb(main):012:0>

**Comment by jyurek** [comment] 2015-06-01 20:26
Can you paste your attachment definition, please, especially your `path` and `url` entries? I'm unable to replicate this error with the standard set that https://github.com/thoughtbot/paperclip_demo provides, so I'd like to see how you have things set up. Thanks.

**Comment by vedant1811** [comment] 2015-06-02 11:09
Here's my full model definition. I have modified the`url` as you can see.

    class V1::Seller < ActiveRecord::Base
      before_create :generate_api_key, :sanitize_file_name
      after_create :send_welcome_email
      after_save :notify

      has_attached_file :image, # paperclip options:
                        :preserve_files => "false",
                        :styles => {:card => '427x240>'},
                        :url => "/:rails_env/#{table_name}/images/:style/:filename",
                        :default_url => ":url/missing.png",
                        :path => ":url",
                        :storage => :s3,
                        :s3_headers => { 'Expires' => 1.year.from_now.httpdate },
                        :s3_credentials => "#{Rails.root}/config/secrets.yml",
                        :bucket => 'instano',
                        :s3_storage_class => :reduced_redundancy
    
      has_many :deals, :class_name => 'V1::Deal', dependent: :destroy
      has_many :quotations, :class_name => 'V1::Quotation', dependent: :destroy
      has_many :brands, :class_name => 'V1::Brand', dependent: :destroy
      has_many :brand_names, :class_name => 'V1::BrandName', through: :brands
      has_many :category_names, :class_name => 'V1::CategoryName', through: :brand_names
      has_many :devices, :class_name => 'V1::Device', dependent: :nullify
      has_many :outlets, :class_name => 'V1::Outlet'

      accepts_nested_attributes_for :brands

      validates :rating, presence: true
      validates :email, presence: true, uniqueness: true

      # paperclip:
      validates_with AttachmentFileNameValidator, :attributes => :image, :matches => [/png\Z/, /jpe?g\Z/]
      validates_with AttachmentContentTypeValidator, :attributes => :image, :content_type => /\Aimage\/.*\Z/
      validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 2.megabytes

      # important! do NOT reorder entries
      enum status: [
        # invisible in app
        :removed,
        :inactive,
        # visible in app
        :unverified,
        :verified,
        :deal_provider
      ]

      scope :visible, -> { where('status >= ?', V1::Seller.statuses[:unverified]) }

      has_secure_password
      has_paper_trail

      def title
        "#{name_of_shop} (#{id})"
      end

      rails_admin do
        configure :status do
          searchable false
        end
        clone_config do
          custom_method :shallow_clone
        end
        list do
          field :name_of_shop
          field :image
          field :description
          field :brand_names
          field :status, :enum
          field :phone
          field :email
          sort_by :created_at
          items_per_page 100
        end
        show do
          field :id
          field :status, :enum
          field :name_of_shop
          field :image
          field :description
          field :outlets
          field :brand_names
          field :phone
          field :email
          field :created_at
          field :updated_at
        end
        edit do # both edit and create
          field :name_of_shop
          field :image
          field :description, :ck_editor
          field :status
          field :email
          # TODO: fix: (also see: https://github.com/sferik/rails_admin/issues/2150)
          field :password
          field :password_confirmation
          field :phone
          field :brands
          field :brand_names do
            label "edit brands"
            help "Use only to edit brands. Do not add/remove categories"
          end
        end
      end

      def self.authenticate(email, password)
        seller = find_by_email(email)
        if seller && seller.authenticate(password)
          seller
        else
          nil
        end
      end

      def assign_categories(params)
        begin
          puts 'starting assign_categories'
          puts params.inspect
          permitted = params.require(:seller).permit(brands: [:name, :category])
          puts permitted.inspect

          self.brands.clear

          permitted[:brands].each do |c|
            next if c[:name].nil? || c[:category].nil?

            category_name = V1::CategoryName.find_by(name: c[:category])
            if category_name
              brand_name = V1::BrandName.find_by(name: c[:name], category_name: category_name)
              self.brand_names << brand_name if brand_name
            end
          end
        rescue ActionController::ParameterMissing => e
          logger.error e
        end
      end

    private
      def sanitize_file_name
        if image_file_name
          extension = File.extname(image_file_name).downcase
          self.image.instance_write(:file_name, "#{self.name.parameterize('_')}#{extension}")
        end
      end

      def shallow_clone
        self.dup.tap do |seller|
          seller.password = Rails.application.secrets.placeholder_password
          seller.password_confirmation = seller.password
          seller.email = "#{self.email}2"
        end
      end

      # TODO: notify (and handle the case) if status is changed from visible to invisible in app
      def notify
        return unless verified? || unverified? || deal_provider?
        require 'modules/gcm_notifier'
        GcmNotifier.seller_updated(self)
      end

      def send_welcome_email
        InstanoMailer.welcome_email(self).deliver_later if verified?
      end

      def generate_api_key
        begin
          self.api_key = SecureRandom.hex
        end while self.class.exists?(api_key: api_key)
      end
    end

**Comment by tute** [comment] 2016-03-24 01:04
Is this still an issue for you,  @vedant1811?

**Comment by vedant1811** [comment] 2016-03-25 04:53
I didn't check recently.

Could someone else verify whether this was fixed?

Regards,
Vedant.

**Comment by tute** [comment] 2016-05-09 19:52
Closing this, as we can't reproduce. If it's still an issue, we'll reopen. Thanks!

**Closed by tute** 2016-05-09 19:52 UTC
Labels: Cannot Reproduce, More info needed
