### ISSUE TITLE
A lot of temp files which are not explicitly unlinked

### ISSUE THREAD

**Issue by svetlins** [thoughtbot/paperclip#1326] opened 2013-08-29 08:15 UTC
Hello,

On resizing uploaded images Paperclip creates a lot of Tempfiles (e.g. 6 styles = 13 Tempfiles) which are then not explicitly unlinked. On most Ruby implementations this is OK since the actual files are deleted when the Tempfiles instances are garbage collected. This is a problem though with JRuby since version 1.7.4 in which the behavior is changed so that files corresponding to Tempfiles are only deleted on process exit. Because of this our app started filling up /tmp since the upgrade to JRuby 1.7.4.

I would write an issue to JRuby about that but this piece of Ruby documentation discouraged me: http://www.ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#label-Explicit+close

It basically says that both deleting behaviors are allowed and that it's good practice to explicitly unlink created temp files anyway.

Do you think it's possible to add explicit unlinking of all created temp files to Paperclip? That would really help users of latest JRubies!

Best,
Svetlin

**Comment by maclover7** [comment] 2015-03-09 22:06
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by scomma** [comment] 2015-03-25 06:54
This is still an issue for me. We use paperclip to store the attachments on S3, and the task that saves to S3 runs in a Resque job (which naturally executes in its own fork). Could this be a reason the garbage collector isn't kicking in?

**Comment by topherhunt** [comment] 2015-04-20 19:49
Looks like it's an issue for me too (Paperclip **4.2.0**); batch Paperclip operations tend to crash at the following error:

```
An Errno::EMFILE occurred in background at 2015-04-19 22:25:02 -0700 :

 Too many open files - identify -format '%wx%h,%[exif:orientation]' '/tmp/6f53a5e7b68ac7105b51677c0bc3426320150420-23382-17zy612.jpg[0]' 2>/dev/null
```

...which traces back to Paperclip and is discussed more in [this SO question](http://stackoverflow.com/questions/18393580/errnoemfile-too-many-open-files-with-local-images-on-create).

**Comment by bluta** [comment] 2015-05-08 07:01
also for me, (Paperclip 4.2.0, S3, uploading in Resque)
shame on me, I've only realized when it made our EngineYard util instance unusable - filling the 16G /tmp on the root partition.

**Comment by jstorimer** [comment] 2015-07-03 21:43
I'm experiencing this issue on one of my apps as well. My situation is the exact same as @scomma above:

> We use paperclip to store the attachments on S3, and the task that saves to S3 runs in a Resque job 

We also process some paperclip attachments on our app servers and *do not* have a problem with the `/tmp` directory growing on those boxes.

@jyurek mentioned the usage of Tempfile:

> that was part of the benefit of using Tempfiles -- they just go away on GC

but @scomma got the problem with that exactly right in his comment: 

> the task that saves to S3 runs in a Resque job (which naturally executes in its own fork). Could this be a reason the garbage collector isn't kicking in?

A resque worker will fork a new Ruby process to run each job and will, [(by default), end that process](https://github.com/resque/resque/blob/68b43a3a01006abb0aabf0d564967f546ec1e134/lib/resque/worker.rb#L195) with `exit!`. According to the [docs on that method](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-exit-21), using the bang version means that the process exits *immediately*. It won't run at_exit handlers and won't run GC! If the GC doesn't run then any instances of Tempfile that had yet to be GC'd will be orphaned and never unlinked from the system.

This can be verified with an `irb` session:

``` console
$ irb -rtempfile
> tf = Tempfile.new('test')
=> #<Tempfile:/tmp/test20150703-19388-jas6b5>
> File.exist?(tf)
=> true
> exit!
$ ls /tmp/test20150703-19388-jas6b5 && echo yikes
yikes
```

If you run the same session, but use `exit` instead of `exit!`, then the tempfile will be properly cleaned up with a GC run.

This is a known issue with https://github.com/resque/resque/issues/1167. The suggested fix there is to set `ENV['RUN_AT_EXIT_HOOKS']` so that `exit` is used over `exit!`. 

My leftover tempfile issue was reproducible in my dev environment and this resque config change did fix the issue for me :+1:

**Comment by Dagnan** [comment] 2015-11-20 20:31
Any way to prevent tempfile creation (in my case I'm uploading an already existing file on the system, without any resize because it's an audio file), in a long running task.

**Comment by jeremywadsack** [comment] 2016-03-16 18:34
Thanks to @jstorimer for the analysis. We have the same problem as described (resque jobs) and changing the `~/.bashrc` on our worker servers to include this line resolved it:

```
export RUN_AT_EXIT_HOOKS = true
```

(Yes, that's a pretty broad way to fix this.)

It would be nice if paperclip unlinked the tempfiles though, as this continues to be reported.

**Comment by erkki** [comment] 2016-03-23 11:55
If anyone's up for testing #2143 to see if it helps with any of their issues, much appreciated. Warning: not 100% confident this didn't produce new issues so be careful in production :)

**Comment by NeoElit** [comment] 2017-01-13 20:14
Hi, I'm using paperclip (4.3.1). I'm experiencing similar a issues where around 3 tempfiles per attachment is left hanging in the /tmp till passenger kill the process. Is there any hack to avoid this issue?

**Comment by dmitry** [comment] 2017-01-16 14:19
@NeoElit I think there is one - upgrade till the 5.x :)

**Comment by NeoElit** [comment] 2017-01-17 04:11
@dmitry Thanks.. will try that out.

**Comment by germanotm** [comment] 2017-02-10 16:27
@NeoElit 
I'm having problem with temp files that are not unlinked for every paperclip conversion using paperclip 4.3.5. 
I just upgrade to paperclip 5.1.0 and get the same behavior. Simple upgrade will not solve the problem.

**Comment by dmitry** [comment] 2017-02-10 17:47
@germanotm how do you run paperclip conversion, in a rake task or resque?

**Comment by barbolo** [comment] 2017-02-14 16:42
I'm using Paperclip 5.1.0 and I'm also having issues with "too many files open". Not sure if Paperclip is the problem, but I'm really suspecting about it.

I use Sidekiq 4.2.9, but Paperclip doesn't run as a background job. It runs during a request to our web server (running Puma 3.7.0).

I created a controller action that shows me all files supposedly known by the GC. It does something like this:

```ruby
def garbage_collect
  out = []
  ObjectSpace.each_object(File) do |f|
    out << [f.path, f.closed?].join(": ")
  end
  if params[:perform].present?
    ObjectSpace.garbage_collect
  end
  render text: out.join("\n")
end
```

When I call this action I get a huge list of files created by Paperclip saved in /tmp/. Some of them are open, some are closed.

Then, when I pass the parameter `perform`, the Garbage Collect is performed and after that the list of files decreases to 2 ou 3 files.

I'm trying to investigate it more deeply. But for now it seems Paperclip may be the problem.

**Comment by dmitry** [comment] 2017-02-14 17:35
@barbolo have you tried to use paperclip alone, in a ruby script and reproduct the same issue?

**Comment by barbolo** [comment] 2017-02-14 17:41
@dmitry No, I haven't. It wouldn't be so easy to do that.

This is an output from the action above. All files are generated by Paperclip.

```
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1xtax9f.html: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-375ef5.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1sgu6ue.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1h1zeqp.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-7iva0e.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-ivdfwx.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-81a8pt.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1vaq545.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1dppyt5.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-15w6ay5.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-ttgpea.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-4u9b0.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-h0us0y.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-d1j11d.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1b55i5g.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-uwq141.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-g33p4w.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-g33p4w.html: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-115wqjl.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-115wqjl.html: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-mm91iz.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-m88a4o.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1botcaq.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1rckg1u.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-4olj6k.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-14j3qmw.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-pjvxk5.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1v52u3s.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-194lwc5.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-194lwc5.pdf: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-17hysha.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-8g4bcw.pdf: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-17hysha.pdf: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-wd49i.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-wd49i.html: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1xrupnr.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1xrupnr.html: false
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-16qm1a2.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1sscg6f.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-11jms9p.html: true
File: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-vjv1r4.html: true
Paperclip::Tempfile: : true
Paperclip::Tempfile: : true
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-g33p4w.html: false
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-115wqjl.html: false
Paperclip::Tempfile: : true
Paperclip::Tempfile: : true
Paperclip::Tempfile: : true
Tempfile: : true
Paperclip::Tempfile: : true
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-194lwc5.pdf: false
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-17hysha.pdf: false
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-wd49i.html: false
Paperclip::Tempfile: /tmp/9a0364b9e99bb480dd25e1f0284c855520170214-13804-1xrupnr.html: false
```

**Comment by barbolo** [comment] 2017-02-14 17:58
Analyzing logs like the one in the previous message, I can't find any problem. I'm running a server with this application for the last 3 days and about 300 files on `/tmp` were never removed after being used by Paperclip. 

I've run several server (puma) hot restarts in these 3 days, but I don't think it should be a problem.

I'll investigate more. If you have any idea on what I could try, I'll appreciate.

**Comment by dmitry** [comment] 2017-02-14 20:38
@barbolo are you using file adapter to store files, or s3 (aws) or similar?

**Comment by barbolo** [comment] 2017-02-14 20:48
@dmitry I'm using S3 (AWS). The code is below.

I call it, for example this way:

`ReceiptAttachment.generate(other_model, html: "<html>...</html>")`

```ruby
class ReceiptAttachment < ApplicationRecord
  belongs_to :other_model

  has_attached_file :document, {
    url: '/documents/:id_:hash.:extension',
    hash_secret: '...',
    storage: Rails.env.production? ? :s3 : :filesystem,
    path: Rails.env.production? ? ':url' : ':rails_root/public/attachments:url',
    s3_credentials: { ... },
    s3_protocol: 'https'
  }

  do_not_validate_attachment_file_type :document

  def self.generate(other_model, content = {})
    ra = ReceiptAttachment.new(other_model: other_model)
    file = ReceiptAttachment.file_from_content(content)
    ra.document = file
    ra.document_content_type = file.content_type
    ra.save!
  end

  def self.file_from_content(content)
    file = StringIO.new(content[:html] || content[:pdf])
    file.class.class_eval { attr_accessor :original_filename, :content_type}
    if content[:pdf]
      file.original_filename = 'content.pdf'
      file.content_type = 'application/pdf'
    else
      file.original_filename = 'content.html'
      file.content_type = 'text/html'
    end
    file
  end

  def url
    if Rails.env.production?
      self.document.url
    else
      "file://localhost#{self.document.path}"
    end
  end

  def content
    if self.document.present?
      if Rails.env.production?
        Mechanize.new.get(self.url).body.force_encoding('utf-8').to_s
      else
        File.read(self.document.path)
      end
    else
      ''
    end
  end
end

```

**Comment by dmitry** [comment] 2017-02-14 21:14
@barbolo nice, thanks!

Looks like an issue in the `stringio_adapter.rb`. There are no `unlink` method to get rid of created `@tempfile`.

Please add into your `config/initializers` the filename `paperclip_stringio_fix.rb` with the following contents:

```ruby
class Paperclip::StringioAdapter
  def unlink
    @tempfile.unlink
  end
end
```

**Comment by dmitry** [comment] 2017-02-14 21:34
@barbolo nice, thanks!

Looks like an issue in the `stringio_adapter.rb`. There are no `unlink` method to get rid of created `@tempfile` after they were written to the filesystem or network.

Try out the following code, might solve your issue:

```ruby
  def self.file_from_content(content)
    data = StringIO.new(content[:html] || content[:pdf])
    file = Paperclip.io_adapters.for(data)
    if content[:pdf]
      file.original_filename = 'content.pdf'
      file.content_type = 'application/pdf'
    else
      file.original_filename = 'content.html'
      file.content_type = 'text/html'
    end
    file
  end
```

**Comment by barbolo** [comment] 2017-02-15 11:02
@dmitry The problem with too many open files is still occurring. I'll try to use aws-sdk directly instead of Paperclip. Then I'll update this issue telling if the error was gone.

**Comment by kilink** [comment] 2017-03-07 08:36
I've seen Paperclip tempfiles accumulating from a long-running Sidekiq process. I'm using Paperclip 4.3.7 and Sidekiq 4.2.9 on Ruby 2.3.3.

What I have discovered while investigating the issue is that Paperclip will leave tempfiles lingering if a processor throws an exception. For example, we're using paperclip-av-transcoder (0.6.4), and sometimes ffmpeg doesn't like the uploaded file, or it's not a valid video, and an execption is thrown. Examining the Attachment object after such an exception, you will see that the `queued_for_writes` and `file` attributes both refer to tempfiles.

When an exception isn't thrown, these tempfiles get unlinked when [after_flush_writes](https://github.com/thoughtbot/paperclip/blob/v4.3/lib/paperclip/attachment.rb#L576) is called when your model is saved. In our case, when an exception occurs, we are not saving the model, so this callback is never run.

Under normal circumstances, these lingering tempfiles wouldn't be a problem, because the Ruby GC would eventually clean them up. Now, I am not a Ruby expert by any means, so this is all wild speculation, but I suspect that a long running process where the heap grows large enough may see significantly fewer major GCs, thus exacerbating this issue. There is also a circular reference between the Paperclip::Attachment instance and the Model instance, which I am guessing means it is less likely to die in "eden" space and thus stick around longer.

Anyway, here is my hacky solution: wrap the paperclipping code in a begin / rescue, and if an exception is thrown, do the following to remove any tempfiles:

```ruby
upload.paperclip.send(:after_flush_writes)
upload.paperclip.queued_for_write.clear
```

Which is essentially just looping through all of the values in the `queued_for_write` map and calling close and unlink on them.

Now, how would this actually be fixed in Paperclip proper? I'm guessing by adding similar clean up code in either the [assign](https://github.com/thoughtbot/paperclip/blob/v4.3/lib/paperclip/attachment.rb#L97) method or one of the post_process methods.

**Comment by NeoElit** [comment] 2017-04-20 19:33
@kilink Thanks..
That solution resolves issue to an extend for me.

I was using `Paperclip::Geometry.from_file(attachment.queued_for_write[:original].path)` to validate image width and height which will raise `Paperclip::Errors::NotIdentifiedByImageMagickError` in case imagemagick doesn't respond well. If not rescued and manually handled, all the temp files from paperclip seems to accumulate.

However RackMultipart* temp files from passenger seems to float around even after that. I'm not sure whose job is to clear that off. Is it the job of passenger or paperclip? I could see it cleaned up when passenger is stopped.

**Comment by dmitry** [comment] 2017-05-30 11:53
Original file not closed when it's not selected for reprocessing. Could be closed with `instance_variable_get(:@file).close`. Issue somewhere in the `post_process_style`

**Comment by mike-burns** [comment] 2018-04-27 20:12
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Closed by mike-burns** 2018-04-27 20:12 UTC

**Comment by filipeperdigaosousa** [comment] 2018-05-21 23:09
Any news about that?

I'm trying to initialize a thousand of models with attachments but after a dozen of instances it results in the too many files open error.

`
      file = Tempfile.new(["#{DateTime.now.to_i}", ".jpg"])
      file.binmode
      file.write(Avatarly.generate_avatar(org.name, size: 600))
      file.read
      begin
        model.picture.content = file
      ensure
        file.close
        file.unlink
      end
`

**Comment by dmitry** [comment] 2018-05-22 18:49
What says `lsof`?

**Comment by urielnaor-flywire** [comment] 2021-10-21 12:32
Hi have the same problem how did you solve it?
