### ISSUE TITLE
Rails Asset Pipeline and Hashing

### ISSUE THREAD

**Issue by etcook** [thoughtbot/paperclip#1335] opened 2013-09-04 23:06 UTC
Whenever you set the default_url for an attachment, the resulting path isn't hashed according to the compilation. Is this the intended behavior? Are you supposed to place the image in the asset pipeline, or public?

It doesn't help that ActionController::Base.helpers.asset_path doesn't output the asset path properly.

**Comment by maclover7** [comment] 2015-03-09 22:07
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by fabiolnm** [comment] 2015-03-12 06:57
Having the same issue, had to solve using proposed workaround.

**Comment by AbeCole** [comment] 2015-03-16 14:21
@maclover7 Not sure if I've missed something but the issue still seems to be caused. Have just had it happen on a fresh Rails 4.2 app with paperclip 4.2.1

**Comment by maclover7** [comment] 2015-03-16 23:51
@AbeCole Do you have the code that's causing you the issue?

**Comment by AbeCole** [comment] 2015-03-17 14:43
@maclover7 Have just made a test application and deployed in production see here http://178.79.162.235:83/people/1. Repo here: https://github.com/AbeCole/paperclip_test

From a fresh rails app only changes are creating the Person scaffold, adding paperclip to it and adding Capistrano for deployment. 

There is a 'missing.svg' that resides in /assets/images, and my model should reference this using the following code (if I've understood everything correctly):

has_attached_file :image, :default_url => '/assets/missing.svg', :styles => {:thumb => "80x80#", :icon => "36x36#"}

**Comment by maclover7** [comment] 2015-03-21 12:43
@AbeCole, maybe I'm misunderstanding the issue. The Rails app you have deployed appears to be working fine. What is the issue we're trying to solve here?

**Comment by AbeCole** [comment] 2015-03-21 14:23
@maclover7 The issue is something to do with Paperclip and the Assets pipeline. On the page I linked to the 'default_url' image is not being loaded because it isn't included in the assets pipeline.

**Comment by morganick** [comment] 2015-05-28 20:54
@maclover7 I think I can exemplify the issue with default url pretty well. I have the following attachment definition:

```ruby
  has_attached_file :app_logo,
                    default_url: 'missing/:attachment/:style/missing.png',
                    styles: { normal: "x39", email: "224x56", retina: "x78" }

```

First, my `default_url` does not point to an asset in the public directory. Second, my `default_url` is interpolated because we serve a retina and normal to the UI even with the missing image.

Now when the asset pipeline looks at this URL it doesn't find the asset because the string has not been interpolated yet. Hence why you cannot simply:
```ruby
  has_attached_file :app_logo,
                    default_url: ActionController::Base.helpers.asset_path('missing/:attachment/:style/missing.png'),
                    styles: { normal: "x39", email: "224x56", retina: "x78" }
```

I looked into doing my own interpolation for the entire url; however, I don't want to create a custom interpolation for the entire URL for each attachment. (Not all attachments have the same file extension.)

I found another method for doing a custom interpolator, however, it doesn't play nicely with `fog_base_url` and ends up putting a double `/` after the host and before the asset path. (e.g. `http://example.com//assets/foo.png`. Here is the module I tried:

```ruby
module Paperclip
  module AssetPipeline
    class Interpolator
      def self.interpolate(pattern, *args)
        ActionController::Base.helpers.asset_path Paperclip::Interpolations.interpolate(pattern, *args)
      end
    end
  end
end

```

All I want is to specify the default url as:
```ruby
  has_attached_file :app_logo,
                    default_url: 'missing/:attachment/:style/missing.png',
                    styles: { normal: "x39", email: "224x56", retina: "x78" }

```

and end up with:
```
http://localhost:3000/assets/missing/app_logos/normal/missing.png
```

Any suggestions?

**Comment by tute** [comment] 2016-05-10 22:11
This is not a direct fix for the issue, but I think `default_url` is an anti-pattern in paperclip. I totally agree with http://stackoverflow.com/a/7267740/356060: that's a view concern, and should probably belong in a presenter or helper. Again, knowing this is not a fix, would it overcome the issues you are having?

**Comment by josepanguera** [comment] 2017-03-23 00:32
An alternative solution to @sumitngupta fix, so it is no necessary to modify every attachment:

    class UrlGeneratorHack < Paperclip::UrlGenerator
      def for(style_name, options)
        url = super
        url = ActionController::Base.helpers.asset_path(url) if url.start_with?("missing")
        url
      end
    end

    Paperclip::Attachment.default_options.merge!(
        :default_url => "missing/:class/:attachment_:style.png",
        :url_generator => UrlGeneratorHack,
    )

**Comment by mike-burns** [comment] 2018-04-27 20:13
People found workarounds, closing.

**Closed by mike-burns** 2018-04-27 20:13 UTC
