### ISSUE TITLE
AWS Version 2 support - uninitialized constant Paperclip::Storage::S3::AWS

### ISSUE THREAD

**Issue by fuzzyjulz** [thoughtbot/paperclip#1764] opened 2015-02-09 00:43 UTC
It appears that the latest version of AWS - version 2, is not compatible with paperclip. From the aws-sdk-ruby:

> NameError: uninitialized constant AWS
>
>If you receive this error, you likely have upgraded to version 2 of the aws-sdk gem unintentionally. Version 2 uses the Aws namespace, not AWS. This allows version 1 and version 2 to be used in the same application.
> http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2

Is there a plan to do the upgrade?

**Comment by darylprickett** [comment] 2015-02-11 17:06
In the meantime the readme should probably be changed from 
gem 'aws-sdk', '~> 1.5.7'
to
gem 'aws-sdk', '< 2.0'

More information:
http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2

**Comment by hughevans** [comment] 2015-02-12 03:41
How to switch to fog:

```diff
   config.upload_file_options = {
-    storage: :s3,
-    s3_credentials: {
-      bucket:            ENV['FOG_DIRECTORY'],
-      access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
-      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
+    storage: :fog,
+    fog_credentials: {
+      aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
+      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
+      provider: ENV['FOG_PROVIDER'],
+      region: ENV['FOG_REGION'],
+      scheme: 'https'
     },
-    s3_headers: {
+    fog_directory: ENV['FOG_DIRECTORY'],
+    fog_file: {
       'Cache-Control' => 'max-age=315576000',
       'Expires'       => 10.years.from_now.httpdate
     },
-    url: ':s3_alias_url',
-    s3_host_alias: '/',
     path: 'files/:hash_:style.:extension',
     hash_secret: ENV['SECRET_KEY_BASE']
   }
```

**Comment by fuzzyjulz** [comment] 2015-02-12 05:56
Hmmm but that is just changing the implementation for the Fog one.

What is the recommended approach? I would have thought that using the official amazon SDK would be better. If not then is paperclip looking to drop direct support for s3?

**Comment by uberllama** [comment] 2015-02-23 19:14
+1 for v2 aws-sdk support. A lot of work has gone into this release.

**Comment by kenn** [comment] 2015-02-26 05:13
:+1: for aws-sdk v2

**Comment by ArmandPredicSis** [comment] 2015-02-27 16:16
:+1:

**Comment by 0000marcell** [comment] 2015-02-28 14:11
:+1: for aws-sdk v2

**Comment by DavidMMelin** [comment] 2015-03-05 00:48
:+1:

**Comment by sambecker** [comment] 2015-03-05 17:28
👍

**Comment by eduardohertz** [comment] 2015-03-05 18:00
:+1:

**Comment by Fredar** [comment] 2015-03-05 21:43
:+1:

**Comment by chirag7jain** [comment] 2015-03-10 05:37
+1

**Comment by hectorpalmatellez** [comment] 2015-03-13 02:47
:+1:

**Comment by djdrzzy** [comment] 2015-03-16 17:22
+1

**Comment by brettv** [comment] 2015-03-16 18:06
What do the project maintainers intend to do or recommend doing?.  I don't
actually have a strong preference one way or the other.  I just want to
know so I can plan accordingly.


On Mon, Mar 16, 2015 at 11:23 AM, Daniel Drzimotta <notifications@github.com

**Comment by rselk** [comment] 2015-03-16 21:07
(Y)

**Comment by darcy-kudos** [comment] 2015-03-16 21:09
:+1:

**Comment by gt-sdi** [comment] 2015-03-16 21:22
:+1:

**Comment by gabskoro** [comment] 2015-03-17 08:50
:+1:

**Comment by robertg** [comment] 2015-03-17 09:39
:+1:

**Comment by brunoluigi** [comment] 2015-03-18 21:27
:+1:

**Comment by andrelaszlo** [comment] 2015-03-22 15:16
:+1:

**Comment by betesh** [comment] 2015-03-25 21:33
:+1:

**Comment by djvs** [comment] 2015-03-31 03:54
What on earth is going on here?

**Comment by ChihuahuaPunk** [comment] 2015-03-31 14:30
:+1:

**Comment by djvs** [comment] 2015-03-31 14:51
Can you detect which gem version is present and then just change the implementation accordingly?

**Comment by maclover7** [comment] 2015-04-09 23:56
It's great to have everyone :+1: -ing, but would anyone want to submit a PR too for v2 support?

**Comment by betesh** [comment] 2015-04-22 20:10
I started a branch here: betesh/paperclip (aws_v2 branch)

It's a good start and I welcome further contributions from the crowd. spec/paperclip/storage/s3_live_spec.rb is passing, but spec/paperclip/storage/s3_spec.rb and integration_spec.rb need a lot of work.

Also, the type of error that the S3 Client can raise have changed, and I have not been able to find a good reference on them, so most of `rescue` arguments are classes that don't exist anymore.

Lastly, `Paperclip::Storage::S3#exists?` has inadequate testing.

**Comment by davetchen** [comment] 2015-04-23 10:52
Great to see work on a new branch! We're actually using both versions of the aws-sdk in our project at the same time using the method described in the referenced AWS blogpost: http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2
```
# Gemfile
gem 'aws-sdk-v1'
gem 'aws-sdk', '~> 2'
 
# in code
require 'aws-sdk-v1'
require 'aws-sdk'
```
In this case, I would want paperclip to grab the v2 sdk rather than the v1. Do you think folks might want to explicitly select one version or the other by having unique `:storage` options?

@betesh, you can find information on the new S3 error classes here: http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Errors.html

**Comment by betesh** [comment] 2015-04-23 22:54
@davetchen While I understand the reason for wanting to select which SDK version to use, I don't think 2 separate classes is necessary--it would lead to a lot more duplication than it's worth for just a few lines of code differences.  Maybe if they are 2 subclasses and most of the implementation is in the parent then it would be reasonable, but even so, the main effort will be in adding a configuration option, not in re-structuring the underlying code.

Before I proceed, I need to know @thoughtbot's opinion on this--I don't want to go down the wrong path and have the effort go to waste.

**Comment by davetchen** [comment] 2015-04-24 17:57
Yes that makes sense. I'm OK with the single "s3" storage option--just throwing it out there in case others thought differently. However, our application definitely prefers the aws-sdk-v2 over the v1 (it is more aware of differences between regions, "signing" requirements, etc.). We need to include both in our Gemfile for legacy reasons but would then suggest reversing the logic here:

    const_set('AWS_CLASS', defined?(::AWS) ? ::AWS : ::Aws)

**Comment by trevorrowe** [comment] 2015-05-19 04:01
@betesh @davetchen Sorry for being so late the party. I took a look at the branch and left a few comments here: https://github.com/betesh/paperclip/commit/d2e368b827c942f02682c8a4a1047231802b8bef

Overall the approach works well.  I notice that it defaults to the v1 SDK when both are present. @davetchen mentioned that it should default to v2 when both are present, which I agree with. For this to happen, there is a certain amount of work needed to translate some of the v1 configuration options to v2. Most of the differences can be smoothed over and I'd be happy to contribute or provide guidance on these. 

Something to consider, I would consider abstracting the v1 and v2 SDK into a single interface where the s3 storage engine could work indifferently with the SDK. I'd be happy to discuss some options on this here, on the linked branch: https://github.com/betesh/paperclip or in the Ruby SDK gitter channel: http://gitter.im/aws/aws-sdk-ruby

Lastly, I'm not against a new storage engine. I would be really interested in getting feedback from the paperclip maintainers. @jyurek Any thoughts?

**Comment by betesh** [comment] 2015-05-19 12:59
@trevorrowe Thanks for the feedback, I really appreciate it.

Are we assuming that my aws_v2 branch will eventually be merged as the solution to this issue?  If so, either thoughtbot could pull the branch into the main repo so that people could continue submitting PRs for this branch directly to thoughbot, or people could just submit PR's directly to my aws_v2 branch and I'll merge them and when it's ready, I'll open a single PR with thoughbot.  I'm open to either route.

I wish I had time to continue contributing right now, but I have very little time for this lately, so I think it's best if we encourage everyone to contribute to the effort on a single branch.

**Comment by trevorrowe** [comment] 2015-05-19 16:08
@betesh I think we need comments from thoughtbot on what direction they would be inclined to support. I'm happy to continue contributing to your branch. I'll try to take some of the feedback I left on your commit and put them together as a pull request today.

I'm on the fence about wether to modify the existing `:s3` storage engine or to simply add a new one, such as `:aws_sdk`. Given the v1 SDK is very near end of life, I don't see the current engine needing changes. That said, there is a decent amount of code around the storage engine that is not interfacing the SDK directly.

I'll be happy to contribute either way.

**Comment by tute** [comment] 2015-05-20 03:27
@jyurek we should address this issue before we release 4.3.0.

**Comment by davetchen** [comment] 2015-05-20 17:05
@betesh and @trevorrowe , left a pull request for changes here:
https://github.com/CloudVLab/paperclip/commit/7879954b42e1ebb6e37776ed3f60061e7283dab1

Seems to be working! Doing more tests...

**Comment by betesh** [comment] 2015-05-20 19:19
@davetchen's PR is merged into the aws_v2 branch

**Comment by xtagon** [comment] 2015-05-22 21:02
@davetchen Did you mean you are able to use both v1 and v2 of the SDK in a project using Paperclip? I have a project using Paperclip and I'd like to use the v2 SDK for other purposes, but when I use the method you described to require both versions, Paperclip fails to generate a correct presigned POST when I do my uploads. I'm seeing the following error from S3

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    ...redacted details...
</Error>
```

Any ideas? Is aws_v2 branch considered okay for production? I don't care what version Paperclip uses, I just want to be using v2 in the same project.

**Comment by davetchen** [comment] 2015-05-22 21:31
It is working for me in a project with both aws-sdk-v1 and aws-sdk-v2, but haven't tested all use cases. If you're using the version from `source 'https://rubygems.org'` then Paperclip will be using aws-sdk-v1. Which region is your S3 bucket in?

**Comment by xtagon** [comment] 2015-05-23 00:03
Region is US-Standard. As far as I can tell, the only thing that doesn't work is generating presigned POST params with Paperclip. Maybe I can just rewrite my code to sign it with the SDK v2 directly.

**Comment by xtagon** [comment] 2015-05-23 05:16
My development environment was set up incorrectly and the problem was unrelated to Paperclip. Everything works now with both versions, sorry for the false alarm. :)

**Comment by davetchen** [comment] 2015-05-25 15:55
Sounds good @xtagon! Did you end up trying the aws_v2 branch?

**Comment by xtagon** [comment] 2015-05-27 04:15
Haven't gotten around to it yet since v1 and v2 work fine side by side. I'll test it when I get a chance and report any issue if I find any.

**Comment by davetchen** [comment] 2015-06-05 18:00
@betesh : I've been using the aws_v2 branch in production for a couple weeks with no issues. Do you think it's ready for a PR?

**Comment by betesh** [comment] 2015-06-05 20:02
@davetchen The problem is not all the tests pass.  I just pushed a commit (after rebasing onto master) with one example of getting a few tests to pass when stubbing, but there's still a lot of work to be done on this end.

**Comment by davetchen** [comment] 2015-06-08 12:58
Understood, I'll take a look at your commit.

**Comment by davetchen** [comment] 2015-06-09 00:30
@betesh I'm trying to setup the testing as described here: https://github.com/thoughtbot/paperclip/blob/master/CONTRIBUTING.md

The 'bundle' command has been running for the last 3 hours ... do you have an easier way to set it up? To see what is going on I set `DEBUG_RESOLVER=1` as per:
http://patshaughnessy.net/2011/9/24/how-does-bundler-bundle

it's still 'iterating'...

**Comment by betesh** [comment] 2015-06-09 15:10
I just did a bundle update and it took a few minutes but nothing crazy.  I don't recall this happening during the first bundle install either.

I didn't to an appraisal install--I figured once tests are passing with 1 Gemfile, I'll open up my branch to travis to get a first approximation of any issues, before trying to debug all Gemfiles locally.

**Comment by davetchen** [comment] 2015-06-09 18:24
I think the problem is trying to find the right version of the 'rubysl' gem. I'm using ruby-1.9.3 and trying to install

``gem install rubysl -v '~> 2.0.12'``

There is a conflict with 'rubysl-benchmark' which has a dependency on ruby-2. Which ruby are you using?

**Comment by betesh** [comment] 2015-06-09 19:19
I'm using ruby-2.1.5

**Comment by davetchen** [comment] 2015-06-09 19:41
OK -- just switched to ruby-2.1.6 and now I can run the tests (that was easy). I'm seeing 40 or so failures in the S3 storage spec of the form:
```
rspec ./spec/paperclip/storage/s3_spec.rb:94 # Paperclip::Storage::S3 missing :bucket option raises an argument error
rspec ./spec/paperclip/storage/s3_spec.rb:116 # Paperclip::Storage::S3  uses the correct bucket
rspec ./spec/paperclip/storage/s3_spec.rb:120 # Paperclip::Storage::S3  uses the correct key
...
```
Will start looking at these.

**Comment by davetchen** [comment] 2015-07-31 23:18
Hi Betesh -- just wondering about the status of the pull request. Are there other actions that need to be taken? 
-dave

**Comment by betesh** [comment] 2015-08-03 14:01
Not in my opinion.  In my last 2 comments on #1903 (https://github.com/thoughtbot/paperclip/pull/1903#issuecomment-113193016, https://github.com/thoughtbot/paperclip/pull/1903#issuecomment-114890199), I asked for feedback on the 2 issues people were still discussing, but I have received no feedback.

I just rebased it onto upstream/master.  Give Travis an hour or 2 and then if everything passes, I'm ready for it to be merged.

**Comment by betesh** [comment] 2015-08-17 21:07
Is anyone planning on merging this?

**Comment by jferris** [comment] 2015-08-18 18:30
@davetchen @betesh sorry for the delay here. We're running a little behind right now because of vacations, our company retreat, and some other distractions. We're not sure when we'll be able to look at this, but we haven't forgotten about Paperclip and we'll get it merged as soon as we can.

**Comment by davetchen** [comment] 2015-08-19 15:56
Thanks for the update. Moving forwards more and more folks will be wanting to standardize on using the aws-sdk-v2, both for accessing new regions and new services.

**Comment by rept** [comment] 2015-08-23 23:15
:+1:

**Comment by josedonizetti** [comment] 2015-09-02 17:44
any plans to have this merged?

**Comment by jyurek** [comment] 2015-09-02 18:08
#1903 was merged just about 2 weeks ago.

**Closed by jyurek** 2015-09-02 18:08 UTC
Labels: Bug, Convert to PR
