### ISSUE TITLE
/tmp fills up with remote files during migration

### ISSUE THREAD

**Issue by walterdavis** [thoughtbot/paperclip#2030] opened 2015-10-20 22:28 UTC
I am following this example: https://github.com/thoughtbot/paperclip/wiki/Attachment-downloaded-from-a-URL to access files from a previous Paperclip application and load them into a new application. All files are stored on S3. As I do this in a Rails console loop, and there are thousands of them, I discovered that the files appear to be "stashed" in /tmp by open-uri, and they remain there until deleted. I found this out because my /tmp directory grew to encompass all space on my drive. I worked around it by adding a step to my loop that deleted any file in /tmp that had the same name as the one I was downloading. But since open-uri is supposed to clean up after itself when it is invoked inside a block, I don't believe this should be necessary. Here's what's working now, after a fashion:

~~~rb
Asset.find_each do |a|
  begin
    # this is a special URL that returns the text URL of the original file on S3
    file = open("http://example.com/assets/#{a.id}/raw_file").read
    a.blob_remote_url = file
    a.save
  rescue
    a.destroy
  ensure
    FileUtils.rm Dir.glob("/tmp/#{File.basename(file)}.*")
    FileUtils.rm Dir.glob("/tmp/open-uri*")
  end
end
~~~

It just feels wrong to have to do things this way. Any suggestions?

Walter

**Comment by dmitry** [comment] 2015-10-23 15:21
Check out this one: https://github.com/thoughtbot/paperclip/issues/1326

**Comment by tute** [comment] 2016-05-10 15:56
Closing as duplicate of #1326. Thanks!

**Closed by tute** 2016-05-10 15:56 UTC
