### ISSUE TITLE
Why is NotIdentifiedByImageMagickError raised?

### ISSUE THREAD

**Issue by mattgreen** [thoughtbot/paperclip#1040] opened 2012-10-09 14:54 UTC
I'm confused as to why `NotIdentifiedByImageMagickError` is even raised. The contributing guidelines emphasize the need to use Rails idioms as much as possible, but raising an exception is, well, not very common when writing Rails apps. It doesn't qualify as a truly exceptional condition; it is possible to trigger it by uploading a PDF without having Ghostscript installed.

Ideally, it should fail to assign, and then add a validation error to the model it is attached to.

**Comment by maclover7** [comment] 2015-03-09 21:04
Hi @mattgreen ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by mattgreen** [comment] 2015-03-10 20:36
It doesn't affect me anymore, but it still looks like it's a problem (based on a cursory glance of the code).

**Comment by tute** [comment] 2015-05-25 15:44
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1223.

**Closed by tute** 2015-05-25 15:44 UTC
Labels: Bug, Convert to PR
