### ISSUE TITLE
upgrade from 3.5.2 to 3.5.3 wont delete path after destroy

### ISSUE THREAD

**Issue by erpe** [thoughtbot/paperclip#1424] opened 2014-01-25 21:34 UTC
```ruby
it 'erases data-file if destroyed' do
    asset = FactoryGirl.create(:asset)
    path = asset.data.path
    asset.destroy
    File.exists?(path).should be_false
end
```

**Comment by maclover7** [comment] 2015-03-09 22:27
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment] 2015-05-15 03:06
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1445.

**Closed by tute** 2015-05-15 03:06 UTC
