### ISSUE TITLE
after_commit is deprecated in Rails 4.2

### ISSUE THREAD

**Issue by emn178** [thoughtbot/paperclip#1933] opened 2015-07-12 07:26 UTC
Hi,

after_commit is deprecated in Rails 4.2, so I get this warning:

DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

Please help to fix it.

Thanks & best regards.

**Comment by coorasse** [comment] 2015-07-18 19:25
Yes, very annoying also for me. Rails@4.2 and paperclip@4.3.0

**Comment by voltechs** [comment] 2015-08-04 18:33
+1

**Comment by simonrentzke** [comment] 2015-08-12 07:11
@emn178 the methods `after_rollback` and `after_commit` are not being deprecated, it's just a warning that you need to add `config.active_record.raise_in_transactional_callbacks = true` to your config. Which you can configure to either suppress or raise if an error occurs.

**Comment by fmh** [comment] 2015-08-12 21:45
+1

**Comment by maclover7** [comment] 2015-10-22 02:09
Hi @emn178! Would be willing to submit a PR to fix these errors? Thanks!

**Comment by emn178** [comment] 2015-10-22 02:51
HI,

I trace the paperclip code of this part, I think it's better not to change it.
```Ruby
    def add_active_record_callbacks
      name = @name
      @klass.send(:after_save) { send(name).send(:save) }
      @klass.send(:before_destroy) { send(name).send(:queue_all_for_delete) }
      if @klass.respond_to?(:after_commit)
        @klass.send(:after_commit, on: :destroy) do
          send(name).send(:flush_deletes)
        end
      else
        @klass.send(:after_destroy) { send(name).send(:flush_deletes) }
      end
    end
```
It can ensure the record is deleted.

I set `config.active_record.raise_in_transactional_callbacks = true` to config currently, just like @simonrentzke said.
As the message, it maybe not display warning In the next Rails version.

**Comment by Erowlin** [comment] 2016-01-07 09:29
+1, I believe Paperclip has nothing to do with this warning message, it just warn of how after_commit and after_rollback will work in future versions (more details here https://github.com/rails/rails/pull/14488 and https://github.com/rails/rails/pull/16537).

**Comment by bbiglari** [comment] 2016-01-08 06:04
This is an error to me. The message shouldn't warn me every time and if something will be change in the future, it should show up in the documentation of framework no in every access to database or function call. 

Could you please resolve this issue? this gives me headache every time I am running tests or access to model objects.

Thanks

**Comment by Erowlin** [comment] 2016-01-09 15:11
@bbiglari if you had read the rails/rails#16537, you should have seen this : 

>Add option to stop swallowing standard errors on after_commit and after_rollback.
Currently the option will be +false+ and throw a warning untill set it to +true+.
Example:
>For not swallow errors in after_commit/after_rollback callbacks.
`config.active_record.errors_in_transactional_callbacks = true`

**Comment by bbiglari** [comment] 2016-01-09 16:24
I have this in my Sinatra app, but doesn't resolve my issue. Also this is
not an ultimate solution.


Best,
Bahador Biglari,

Your big opportunity may be right where you are now -- Napoleon Hill

**Comment by Erowlin** [comment] 2016-01-11 11:02
I think you don't want to understand what I wrote. 
The warning showed is NOT a regression NOR a bad behaviour. 

Actual Behaviour for after_commit / after_rollback : When there is an error, the error is logged however it's not shallowed. Meaning that the error does not stop the current execution.

Futur Behaviour for after_commit / after_rollback : When there is an error, the error is logged and is not shallowed. Meaning that the error DOES STOP the current execution. 

The warning displayed is only here to inform you of that futur behaviour, and this warning will be removed on futur versions of Rails / ActiveRecord. 

On a Sinatra application, you should do something like this : `ActiveRecord::Base.raise_in_transactional_callbacks =true`

**Comment by sikachu** [comment] 2016-02-08 18:33
I think I understand the problem, but I'm not sure what should be the way to resolve this. I think having Paperclip sets `ActiveRecord::Base.raise_in_transactional_callbacks = true` is too intrusive and a bit too much.

One thing we can do though is to silence the deprecation warning for that particular section. Would that be an acceptable solution?

**Comment by Erowlin** [comment] 2016-02-09 20:00
I don't think Paperclip has something to do. Each user should choose to enable `raise_in_transactional_callbacks` or not.

**Comment by jpickwell** [comment] 2016-02-10 21:01
I agree with @sikachu and @Erowlin.

@bbiglari, this is not a Paperclip issue. If you have a problem with the warning message then set `raise_in_transactional_callbacks` in your initializer. As already mentioned, having Paperclip set this config option is too intrusive. Do you really want Paperclip to make an application-wide decision for you? I don't.

**Comment by bbiglari** [comment] 2016-02-18 05:05
This doesn't work in my case, since I am using paperclip in Sinatra. Also I had this question with active_record group as well, and they mentioned that you will see the warning in this version and for next version, it will abort the process rather than a warning.

**Comment by IevgenRagulin** [comment] 2017-04-21 12:35
Adding this line to the config file hasn't helped me: "config.active_record.raise_in_transactional_callbacks = true", I'm not sure why. This one helped: ActiveRecord::Base.raise_in_transactional_callbacks = true. All my models are in a separate gem that doesn't have Rails, maybe it has something to do with why the config doesn't work for me.

**Comment by mike-burns** [comment] 2018-04-27 20:40
Not a bug, closing.

**Closed by mike-burns** 2018-04-27 20:40 UTC
Labels: Convert to PR
