### ISSUE TITLE
How to store only URL of uploaded file

### ISSUE THREAD

**Issue by HiteshSongra** [thoughtbot/paperclip#1878] opened 2015-05-28 05:17 UTC
Hello Friends,

I need a help on storing the URL of Uploaded image using paperclip on AWS S3.
I don't want auto generate fields in my database, instead of them i just need URL of that field.
I don't want to use any style for re-size the image.

Suppose my field for image is "image", then paperclip add 4 fields to my table as follow
 - image_file_name
 - image_content_type
 - image_file_size
 - image_updated_at

But, instead of them, I just need "image_url" in my database. and whenever i delete record that uploaded image is also delete from AWS S3.

is it possible to do this?

Please advise.

Thanks,
Hitesh

**Comment by tute** [comment] 2015-05-28 13:13
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1867. Please consider asking in StackOverflow too, while we work in paperclip issue tracker. I apologize for not being able to solve this issue in the short term.

**Closed** 2015-05-28 13:13 UTC
Labels: Question/Discussion
