### ISSUE TITLE
Paperclip version 4.2.1 giving "Too many open files" error

### ISSUE THREAD

**Issue by schumacker** [thoughtbot/paperclip#1980] opened 2015-08-31 19:30 UTC
Hi,

Sorry for opening this question again. I saw that this was solved in past versions, but I'm still getting this error: Rack app error: 

Errno::EMFILE: Too many open files - /tmp/RackMultipart20150825-11316-1d06w7p. 

Could you guys confirm to me if the error was already solved? In stackoverflow they said that the limit for multipart concurrent files is now 128 on Rails 4.2 (http://stackoverflow.com/questions/27773368/rails-4-2-internal-server-error-with-maximum-file-multiparts-in-content-reached). However, my system is using version 4.1.8. Can someone help me? 

Thanks!

**Comment by tute** [comment] 2015-09-09 02:25
This is a duplicate of: https://github.com/thoughtbot/paperclip/issues/1326. A workaround is to raise `ulimit` (see https://github.com/thoughtbot/paperclip/issues/1759#issuecomment-72812870). Thanks!

**Closed by tute** 2015-09-09 02:25 UTC
