### ISSUE TITLE
valid? method in before_post_process

### ISSUE THREAD

**Issue by speedo-spin** [thoughtbot/paperclip#1752] opened 2015-01-25 23:31 UTC
Calling `valid?` method prevent  styles generation even if attachment is valid. Is it correct?

Example:
```
class User < ActiveRecord::Base
  # Paperclip
  has_attached_file :photo,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }

  validates_attachment :photo,
                       presence: true,
                       content_type: {content_type: /\Aimage\/.*\Z/},
                       file_name: {matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]},
                       size: {:in => 1..1000.kilobytes}
  validates :name, presence: true

  before_post_process :check_file_size

  private

  def check_file_size
    valid?
    errors[:image_file_size].blank?
  end
```
ok. next

````
u = User.new
u.photo = some_valid_image
u.name = "Bob"
u.save
````
In this example, after record is saved, only default "photo" url is available, all other styles doesn't generated. This is not ok.

But if we skip `valid?` method in `check_file_size` action, paperclip will generate all 'photo' styles, despite the fact that the record is invalid at that step ( 'name' is missing ). We assing name in next step. After record is saved, all styles of attachment are available.

Is this correct behavior? Should paperclip skip style generation when we invoke 'valid?' method (even if attachment is valid)? Or should I assign attachment only when all other attributes are valid, like in the next code:

````
u = User.new
u.name = "Bob"
u.photo = some_valid_image
u.save
````
Attributes are valid (:name) and attachment is valid.  Paperclip generates all defined styles.  Everything is ok.

**Comment by tute** [comment] 2015-05-20 04:22
@speedo-spin this looks like a bug. How can we reproduce it?

@jyurek do you know why could this happen?

**Comment by jyurek** [comment] 2015-05-22 19:43
This could happen if your `error[:image_file_size].blank?` returns `false`. Since that is just an ActiveRecord callback, returning `false` will cancel all other callbacks. Since processing styles is embedded in these callbacks, if you bail out of the callback chain, you will prevent processing. This is how the feature is intended to work. I just confirmed the behavior by putting a `before_post_process` callback into the paperclip_demo code. When it returned `true` the processing happened. When it returned `false` it did not.

But more to the point, @speedo-spin, there is a setting called `check_validity_before_processing` which defaults to `true`. This makes sure the attachment is valid before the processing runs. It should be sufficient for your use. If this is not the case, please let me know.

In the meantime, I'm going to close this. If any of this is wrong or does not jive with how your code is behaving, by all means please make another issue.

**Closed by jyurek** 2015-05-22 19:43 UTC

**Comment by speedo-spin** [comment] 2015-11-03 10:35
thanks
