### ISSUE TITLE
S3 credentials from IAM role not being refreshed

### ISSUE THREAD

**Issue by robinson-spai** [thoughtbot/paperclip#1591] opened 2014-07-07 16:14 UTC
My Rails application is deployed to AWS Elastic Beanstalk using a 64bit Amazon Linux 2014.03 v1.0.1 running Ruby 2.0 (Puma) with Paperclip and S3 configured as follows:

```
config.paperclip_defaults = {
  :storage => :s3,
  :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME']
  },
  :path => "/app/images/:class/:attachment/:id_partition/:style/:filename",
  :default_url => "/assets/missing.jpg",
  :s3_permissions => :private
}
```

I have not specified keys in the s3_credentials because I am using an IAM role on the EC2 instance running the application.

The application starts up, fetches keys from the instance profile data, and functions as expected. However, the application stops being able to interact with S3 as soon as the temporary keys expire. It appears that Paperclip is not fetching new keys when the first set expire. If I restart the app server, the application starts working again, I assume because on restart Paperclip is fetching new temporary keys.

Using
- paperclip 4.1.1
- rails 4.0.0
- aws-sdk 1.5.8

**Comment by maclover7** [comment] 2015-03-10 00:33
Hi @robinson-spai ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by losthismind** [comment] 2015-03-10 13:07
Honestly, since coming up with the workaround of using Paperclip -> Fog -> S3, I haven't bothered to try without Fog since. It would be nice to remove the extra dependency but I haven't had time to try it again. Has the implementation within Paperclip change to better handle role-based credentials?

**Comment by robinson-spai** [comment] 2015-03-10 13:07
Honestly, since coming up with the workaround of using Paperclip -> Fog -> S3, I haven't bothered to try without Fog since. It would be nice to remove the extra dependency but I haven't had time to try it again. Has the implementation within Paperclip change to better handle role-based credentials?

**Comment by kknd113** [comment] 2015-03-23 21:52
This issue is still valid.
It stops working as soon as temporary token expires

**Comment by momolog** [comment] 2015-12-01 11:21
@kknd113 @robinson-spai Could you please give a more detailed description on how to reproduce this problem?

We have done the following: 
1. created a rails app that initializes paperclip (4.2.4) without explicit credentials
2. deployed it to an EC2 instance that has a role with a policy that allows full S3 access
3. opened up a rails console on this machine using `rails c` and 
4. reprocessed an existing paperclip attachment

This kept on working for over 24 hours, without reloading, a time span that is surely longer than the expiration time of the temp keys. 
Our verdict: at least this paperclip version (4.2.4) does not show the problem.

**Comment by jufemaiz** [comment] 2016-08-16 01:04
Can confirm this too.

**Comment by yawnr** [comment] 2016-09-04 18:23
@jufemaiz Sorry, you're confirming that it's still an issue? Or that it no longer exists?

**Comment by jufemaiz** [comment] 2016-09-05 00:56
@yawnr sorry John, as with many people above I've shifted to using Fog as the solution provided by @robinson-spai. Can't confirm if anything's changed since.

I think part of the reason is that Paperclip::S3 is expecting a YAML or equivalent.

http://docs.aws.amazon.com/sdkforruby/api/Aws/InstanceProfileCredentials.html
Aws::InstanceProfileCredentials needs to be the object being used, and then call to credentials each time, allowing Aws gem to manage the refreshing of credentials when required. No caching can be used in this approach, which is a little different from an Environmental Variable approach.

I haven't had time to investigate further, but the merging of bucket with credentials is IMHO problematic, but there's probably a workaround available by doing something like

```ruby
s3_credentials: {
  bucket: 'xxx',
  access_key_id: -> { Aws::InstanceProfileCredentials.new.credentials.access_key_id },
  secret_access_key: -> { Aws::InstanceProfileCredentials.new.credentials.secret_access_key }
}
```

**Comment by jufemaiz** [comment] 2016-11-17 01:48
An update on this, functionality for Fog isn't as good as S3.

I cannot do per-model or per-style public vs private configuration with fog.

**Comment by reedloden** [comment] 2017-03-28 09:12
I cannot reproduce this with latest paperclip and aws-sdk v2. Just removing the credentials from the config causes the `aws-sdk` gem to fetch them via instance profiles. It refreshes them fine as well.

**Comment by rud** [comment] 2018-03-27 08:39
Suggesting this issue is closed as it can no longer be reproduced.

**Closed** 2018-04-27 20:18 UTC
