### ISSUE TITLE
Reprocessing a single style re saves the original

### ISSUE THREAD

**Issue by paolodona** [thoughtbot/paperclip#1804] opened 2015-03-06 11:47 UTC
It appears that calling ```attachment.reproces(:my_style)``` re-saves the original image as well.
This results in an extra upload of the original file to S3 (if you use it), causing extra rountrip / delay (and potentially a new file if your interpolations include :updated_at.

In reality reprocessing a single style should not update the original record I believe, as that has not changed?

This is more apparent if you are using the :only_process option and delayed_paperclip with split processing, eg:

````
    has_attached_file :file,
                      storage: :s3,
                      styles: lambda { |_a| 
                                            {
                                              original: { geometry: "2880x2880>" },
                                              thumb: { geometry: "260x260#" }
                                            }                                            
                      processors: [:rotator, :thumbnail, :paperclip_optimizer],
                      only_process: [:original]

  process_in_background :file, only_process: [:thumb]
````

In the scenario above, I would expect:
* paperclip to process the original on upload
* delayed_paperclip to process :thumb asynchronously (we use sidekiq)

What happens is:
* paperclip processes the original on upload - correct
* delayed_paperclip calls attachment.reprocess!(:thumb) from a sidekiq job - correct
* paperclip re-saves the original again and reprocesses the :thumb - incorrect, only the thumb should be saved / uploaded to S3

the culprit seems to be this bit of code:
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L426

When calling reprocess! passing only certain styles, the original is still @queued_for_write.

I'm happy to try to open a PR for this, but I would like to know if you guys have any suggestion on how to approach this, shall we skip the following if :only_process does not include the original?

https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L107
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L109

Any input is appreciated.

**Comment by jyurek** [comment] 2015-03-13 18:03
This might be true overall, but in your case, the important thing to note here is that you have `original` in your list of styles, which means that `original` gets processed. Since it was processed once, it will/should get processed again, as it might have changed.

If you can find a way around this that makes sense, then, yes, a PR would be good.

**Comment by paolodona** [comment] 2015-03-13 19:02
I would expect the following command:
```
attachment.reprocess!(:thumb)
```
to only reprocess the :thumb, regardless of what styles are listed (original or otherwise). Doesn't that make sense?

**Comment by arronmabrey** [comment] 2015-05-27 11:56
I agree with @paolodona.
It's surprising that the following command also reprocesses the original style.
```
attachment.reprocess!(:thumb)
```

**Comment by morgoth** [comment] 2015-05-29 13:45
I have exactly the same issue, also when using delayed_paperclip gem.

I changed https://github.com/thoughtbot/paperclip/blob/14356d7eccb9175819508d243fb4a92681d11208/lib/paperclip/attachment.rb#L333-L347 definition to include between `assign` and `save`:

```
if style_args.any?
  @queued_for_write.reject! { |style, file| !style_args.include?(style) }
end
```

This works and doesn't resubmit original file (to s3 in my case), but it looks very odd, and I'm really not sure if this is a way to go.

@jyurek If you think that it's ok, I'd be happy to submit a PR (tests are still passing).

**Comment by dramalho** [comment] 2015-05-29 14:07
:+1: if you're specifying a format it's totally surprising to get another reprocessed - and I do know all versions are based on the original and you're probably aiming for consistency - but either make this extremely clear or make reprocessing the original opt-in would be improvements

**Comment by jyurek** [comment] 2015-05-29 15:53
Yes, I agree that `reprocess` should only process what styles you give it, but here's the thing... that's what it appears to be doing for me, both from reinspecting the code and trying my own practical test. Are you sure it's not delayed_paperclip doing this?

My methodology:
Use https://github.com/thoughtbot/paperclip_demo as my app.
Modify the Friend class to have a style `long: "6x600!"`
Save an image
Confirm the image of style `long` exists.
Modify the Friend's `long` style to be `600x6!`
Modify the Friend's `original` style to be `64x64#`
Open a rails console
`f = Friend.last; f.avatar.reprocess!(:long)`
Confirm the `long` style is now 600x6
Confirm the `original` style is the original image.
In console: `f.avatar.reprocess!(:original)`
Confirm the original is now 64x64.

Can someone reproduce or refute this? I would be very interested to hear that this didn't work for any of you. I'm using paperclip master here, ftr.

**Comment by arronmabrey** [comment] 2015-05-29 17:05
@jyurek I can reproduce using the paperclip demo app.

- 1 ) clone / setup application

- 2 ) add s3 credentials
  ```diff
  --- a/config/environment.rb
  +++ b/config/environment.rb
  @@ -3,3 +3,10 @@ require File.expand_path('../application', __FILE__)

   # Initialize the Rails application.
   Rails.application.initialize!
  +
  +  Paperclip::Attachment.default_options[:storage] = :s3
  +  Paperclip::Attachment.default_options[:s3_credentials] = {
  +      :bucket => ENV['AWS_BUCKET'],
  +      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
  +      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  +  }
  ```

- 3 ) create friend and upload avatar through the web ui.

- 4 ) change the medium style from `300x300>` to `250x250>`
  ```diff
  --- a/app/models/friend.rb
  +++ b/app/models/friend.rb
  @@ -7,6 +7,6 @@ class Friend < ActiveRecord::Base
     has_attached_file :avatar, styles: {
       thumb: '100x100>',
       square: '200x200#',
  -    medium: '300x300>'
  +    medium: '250x250>'
  ```

  - 5 ) reprocess medium style from the rails console
  ```
  irb(main):003:0> f = Friend.last
  irb(main):004:0> f.avatar.reprocess!(:medium)
  ```

#### Filtered S3 output
```
[AWS S3 200 0.889476 0 retries] get_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/original/1024x768.jpg")
[AWS S3 200 0.138804 0 retries] head_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")
[AWS S3 204 0.443435 0 retries] delete_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")
[AWS S3 200 0.582097 0 retries] put_object(:acl=>:public_read,:bucket_name=>"...",:content_length=>65140,:content_type=>"image/jpeg",:data=>Paperclip::AttachmentAdapter: 1024x768.jpg,:key=>"friends/avatars/000/000/001/original/1024x768.jpg")
[AWS S3 200 0.199338 0 retries] put_object(:acl=>:public_read,:bucket_name=>"...",:content_length=>9934,:content_type=>"image/jpeg",:data=>Paperclip::FileAdapter: aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm20150529-58256-1st9q3y,:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")
```

Here you can see two `put_object` requests to AWS/S3. One is the original style being re-uploaded, and the other is the reprocessed medium style.

Thanks, 
-- Arron

---

###### Full Irb Output
```
irb(main):003:0> f = Friend.last
irb(main):004:0> f.avatar.reprocess!(:medium)
[paperclip] copying /friends/avatars/000/000/001/original/1024x768.jpg to local file /var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm
[AWS S3 200 0.889476 0 retries] get_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/original/1024x768.jpg")
[AWS S3 200 0.138804 0 retries] head_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")

Command :: file -b --mime-type '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/4f79f5b97bacb3a75a04f2d90eb593b320150529-58256-600ykx'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm[0]' 2>/dev/null
Command :: identify -format %m '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm[0]'
Command :: convert '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm[0]' -auto-orient -resize "250x250>" '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm20150529-58256-1st9q3y'
Command :: file -b --mime '/var/folders/tj/265v1h7x7hz_7pdcfl0hxqfw0000gn/T/aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm20150529-58256-1st9q3y'
[paperclip] deleting /friends/avatars/000/000/001/medium/1024x768.jpg
[AWS S3 204 0.443435 0 retries] delete_object(:bucket_name=>"...",:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")

[paperclip] saving /friends/avatars/000/000/001/original/1024x768.jpg
[AWS S3 200 0.582097 0 retries] put_object(:acl=>:public_read,:bucket_name=>"...",:content_length=>65140,:content_type=>"image/jpeg",:data=>Paperclip::AttachmentAdapter: 1024x768.jpg,:key=>"friends/avatars/000/000/001/original/1024x768.jpg")

[paperclip] saving /friends/avatars/000/000/001/medium/1024x768.jpg
[AWS S3 200 0.199338 0 retries] put_object(:acl=>:public_read,:bucket_name=>"...",:content_length=>9934,:content_type=>"image/jpeg",:data=>Paperclip::FileAdapter: aed1befc3ecfd159af321f79d0d85ed920150529-58256-sy1snm20150529-58256-1st9q3y,:key=>"friends/avatars/000/000/001/medium/1024x768.jpg")

   (0.4ms)  BEGIN
  SQL (0.6ms)  UPDATE "friends" SET "avatar_file_name" = $1, "avatar_updated_at" = $2, "updated_at" = $3 WHERE "friends"."id" = 1  [["avatar_file_name", "1024x768.jpg"], ["avatar_updated_at", "2015-05-29 16:36:51.520633"], ["updated_at", "2015-05-29 16:36:52.898721"]]
   (6.1ms)  COMMIT
=> true
```

**Comment by jyurek** [comment] 2015-05-29 17:10
Oh I see, the problem isn't that the original is getting reprocessed, it's that it's getting re-uploaded. Gotcha. Will investigate further now.

**Comment by jyurek** [comment] 2015-05-29 18:15
Ok, so as I has originally discovered, it's because the original file had been downloaded in the first place. I can make the change to only save specific styles, but it will take a little bit.

In the meantime, I would like to reiterate to the other watchers of the thread that this does NOT reprocess the original style. It only reprocesses the one specified. It does re-upload though. So while `reprocess!` is not intended to be called from user-facing code, it could incur data transfer costs. Thanks for verifying, @arronmabrey.

**Comment by arronmabrey** [comment] 2015-05-29 18:17
:+1:

**Comment by morgoth** [comment] 2015-07-08 11:42
Is there anything I can help with to move it forward?

**Comment by dmitry** [comment] 2015-07-08 11:51
I'm also interested in moving this forward. For the latest 5 years whenever I need to make a reprocess always writing monkeypatches for the rake tasks, that provides ability to reprocess styles without touching original file at all.

**Comment by tute** [comment] 2015-08-24 14:47
@jyurek how can contributors help you solve this? Or, contributors, do you have a solution in mind you can submit in a PR?

**Comment by dmitry** [comment] 2015-08-24 16:28
First of all tests must be written to reproduce an issue. Then I believe `post_process_style` method should be rewritten to resolve the test failure.

**Comment by MarkMurphy** [comment] 2015-11-09 22:13
I've dug into this today to see if I could fix it myself. As it turns out, it's definitely going to involve some significant refactoring.

**Comment by MarkMurphy** [comment] 2015-11-10 17:25
So I've got "something" working. I think this solution will suffice for the time being.

**Closed** 2016-08-19 02:54 UTC

**Comment by tute** [comment] 2016-08-19 02:56
Fixed through https://github.com/thoughtbot/paperclip/pull/1993. Thank you all!
