### ISSUE TITLE
How to Remote url another Server ?

### ISSUE THREAD

**Issue by kenshero** [thoughtbot/paperclip#1982] opened 2015-09-01 20:58 UTC
Sorry my bad english.  

I have 2 Server . 1 Server for keep application use RoR .  1 Server for stroage file pdf use Nodejs.

How to send image to another server? 

I doing create API for upload file with Nodejs for get request  POST image from rails.

Help me please
Thank you.

**Comment by jyurek** [comment] 2015-09-02 14:24
So if I have this straight, you want the upload to come through the Rails app and then to pass that to the Node.js API to store it?

You can look at the storage engines (lib/paperclip/storage/s3.rb, for example) to see how we store files remotely there. If you control both of the systems, you could also look into using something like NFS to mount your image storage onto your Rails server and the files will look like they're on a local filesystem.

**Comment by tute** [comment] 2015-09-09 02:22
Closing as this is not a bug in paperclip's codebase, but we can continue discussion here or in StackOverflow until you solve your particular problem. Thanks!

**Closed by tute** 2015-09-09 02:22 UTC
