### ISSUE TITLE
Strange behaviour with `dup`

### ISSUE THREAD

**Issue by mikecmpbll** [thoughtbot/paperclip#1673] opened 2014-10-14 11:58 UTC
Assuming I have a class called Company with has_attached_file :logo : 

```ruby
# expected:
c = Company.first
c2 = c.dup
c2.logo.instance.id  # => nil

# not expected:
c = Company.first
c.logo # loads the attachment into an instance var
c2 = c.dup
c2.logo.instance.id # => 1
# this means that if we change the logo for c2
c2.logo = Tempfile.new("new_logo")
# it will use our original Company ID for file path interpolation,
# because logo.instance is pointing at the old Company, instead of c2
# and File.file?(c2.logo.path) will return false therefore creating a broken link
```

**Comment by tute** [comment] 2015-05-13 05:56
Closing as duplicate of #1773.

**Closed by tute** 2015-05-13 05:56 UTC
